/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
UUID: b221ebdc-9160-40fe-886f-7cfc817aba87

Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Prime power sums and the function T(x).

KEY RESULTS:
- psi: Chebyshev function ψ(x) = Σ_{n≤x} Λ(n)
- T: Sum of 1/k for prime powers p^k ≤ x with k ≥ 2
- T_eq_sum_primes_log: T(x) = Σ_p Σ_{k=2}^{log_p x} 1/k (1 sorry)
- T_split: T(x) = (1/2)π(√x) + T_ge_3(x) (1 sorry)
- T_ge_3_le: T_ge_3(x) ≤ Σ_{k=3}^{log_2 x} (1/k)x^{1/k} (1 sorry)
- T_ge_3_bound: T_ge_3(x) = O(x^{1/3}) (1 sorry)

NOTE: Aristotle budget was reached. Proofs are partial/incomplete.
These results relate ψ(x) and π(x) via prime power contributions.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 1600000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-- Definition of the Chebyshev function psi(x) as the sum of von Mangoldt function for n <= x. -/
noncomputable def psi (x : ℝ) : ℝ := ∑ n ∈ Finset.range (Nat.floor x + 1), ArithmeticFunction.vonMangoldt n

/-- Definition of T(x) as the sum of 1/k for prime powers p^k <= x with k >= 2. -/
noncomputable def T (x : ℝ) : ℝ :=
  ∑ n ∈ Finset.range (Nat.floor x + 1),
    if h : IsPrimePow n ∧ ¬ n.Prime then
      (1 : ℝ) / (n.factorization.sum (fun _ k => k) : ℝ)
    else 0

/-- T(x) is equal to the sum over primes p <= x of the sum of 1/k for 2 <= k <= log_p(x). -/
lemma T_eq_sum_primes_log (x : ℝ) (hx : 2 ≤ x) :
    T x = ∑ p ∈ Finset.filter Nat.Prime (Finset.range (Nat.floor x + 1)),
      ∑ k ∈ Finset.Icc 2 (Nat.floor (Real.log x / Real.log p)), (1 / k : ℝ) := by
  sorry

/-- Definition of T_ge_3(x) as the sum of 1/k for prime powers p^k <= x with k >= 3. -/
noncomputable def T_ge_3 (x : ℝ) : ℝ :=
  ∑ n ∈ Finset.range (Nat.floor x + 1),
    if h : ∃ p k, Nat.Prime p ∧ 3 ≤ k ∧ n = p^k then
      (1 : ℝ) / (n.factorization.sum (fun _ k => k) : ℝ)
    else 0

/-- T(x) splits into a term for k=2 and a term for k>=3. The k=2 term is (1/2)*pi(sqrt(x)). -/
lemma T_split (x : ℝ) (hx : 2 ≤ x) :
    T x = (1 / 2 : ℝ) * (Nat.primeCounting (Nat.floor (Real.sqrt x))) + T_ge_3 x := by
  sorry

/-- T_ge_3(x) is bounded by the sum of (1/k)*x^(1/k) for k from 3 to log_2(x). -/
lemma T_ge_3_le (x : ℝ) (hx : 2 ≤ x) :
    T_ge_3 x ≤ ∑ k ∈ Finset.Icc 3 (Nat.floor (Real.log x / Real.log 2)), (1 / k : ℝ) * (x ^ (1 / k : ℝ)) := by
  sorry

/-- T_ge_3(x) is O(x^(1/3)). -/
lemma T_ge_3_bound : T_ge_3 =O[Filter.atTop] fun x => x ^ (1 / 3 : ℝ) := by
  sorry

end
