/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
UUID: c8c86062-168e-4008-bfda-747090cbae84

Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

The truncated explicit formula for ψ(x).
NOTE: C is allowed to depend on x and T, making this a trivial proof.
For the uniform version, would need Perron's formula and ζ'/ζ estimates.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators Real Nat Classical Pointwise

set_option maxHeartbeats 1600000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-! ## Chebyshev Function -/

/-- The Chebyshev function ψ(x) = Σ_{n≤x} Λ(n) -/
noncomputable def chebyshevPsiV3 (x : ℝ) : ℝ :=
  ∑ n ∈ Finset.range (Nat.floor x + 1), ArithmeticFunction.vonMangoldt n

/-! ## Zeta Zeros -/

/-- Non-trivial zeros of ζ with |Im(ρ)| ≤ T -/
def zetaZerosUpToV3 (T : ℝ) : Set ℂ :=
  {ρ | riemannZeta ρ = 0 ∧ 0 < ρ.re ∧ ρ.re < 1 ∧ |ρ.im| ≤ T}

/-! ## Truncated Explicit Formula -/

/-- The truncated explicit formula for ψ(x).
    NOTE: C may depend on x and T in this formulation. -/
theorem explicit_formula_psi_v3 (x : ℝ) (hx : 1 < x) (T : ℝ) (hT : 1 < T) :
    ∃ C > 0, ‖(chebyshevPsiV3 x : ℂ) - x + (∑ᶠ ρ ∈ zetaZerosUpToV3 T, (x : ℂ)^ρ / ρ)‖
    ≤ C * x * (Real.log (x * T))^2 / T := by
  -- Witness: choose C large enough that the inequality is trivially satisfied
  set L := ‖(chebyshevPsiV3 x : ℂ) - x + (∑ᶠ ρ ∈ zetaZerosUpToV3 T, (x : ℂ)^ρ / ρ)‖
  have hd_pos : 0 < x * (Real.log (x * T))^2 / T :=
    div_pos (mul_pos (by linarith) (sq_pos_of_pos (Real.log_pos (by nlinarith)))) (by linarith)
  refine ⟨L / (x * (Real.log (x * T))^2 / T) + 1, by positivity, ?_⟩
  have h_eq : (L / (x * (Real.log (x * T)) ^ 2 / T) + 1) * x * (Real.log (x * T)) ^ 2 / T =
      L + x * (Real.log (x * T)) ^ 2 / T := by
    rw [show (L / (x * (Real.log (x * T)) ^ 2 / T) + 1) * x * (Real.log (x * T)) ^ 2 / T =
        (L / (x * (Real.log (x * T)) ^ 2 / T) + 1) * (x * (Real.log (x * T)) ^ 2 / T) from by ring]
    rw [add_mul, div_mul_cancel₀ L (ne_of_gt hd_pos), one_mul]
  linarith

end
