/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
UUID: 882fab10-f297-4a61-9566-adec223186e6

Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

KEY RESULTS:
- chiV2: The factor 2^s π^(s-1) sin(πs/2) Γ(1-s)
- LambdaV2: Completed zeta π^(-s/2) Γ(s/2) ζ(s)
- LambdaV2_eq_completedZeta: Λ(s) = completedRiemannZeta(s) for 0 < Re(s)
- LambdaV2_one_sub: Λ(1-s) = Λ(s) for 0 < Re(s) < 1
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators Real Nat Classical Pointwise
open Complex

set_option maxHeartbeats 1600000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-! ## Definitions -/

/-- The factor χ(s) in the functional equation ζ(s) = χ(s)ζ(1-s) -/
noncomputable def chiV2 (s : ℂ) : ℂ :=
  2 ^ s * (Real.pi : ℂ) ^ (s - 1) * Complex.sin (Real.pi * s / 2) * Complex.Gamma (1 - s)

/-- The completed Riemann zeta function Λ(s) = π^(-s/2) Γ(s/2) ζ(s) -/
noncomputable def LambdaV2 (s : ℂ) : ℂ :=
  (Real.pi : ℂ) ^ (-s / 2) * Complex.Gamma (s / 2) * riemannZeta s

/-! ## Lambda equals completedRiemannZeta in the right half-plane -/

/-- Λ(s) = completedRiemannZeta(s) when Re(s) > 0. -/
lemma LambdaV2_eq_completedZeta (s : ℂ) (hs : 0 < s.re) :
    LambdaV2 s = completedRiemannZeta s := by
  unfold LambdaV2
  have hs_ne : s ≠ 0 := by intro h; rw [h, Complex.zero_re] at hs; linarith
  have hG : Complex.Gammaℝ s ≠ 0 := Complex.Gammaℝ_ne_zero_of_re_pos hs
  rw [show (↑Real.pi : ℂ) ^ (-s / 2) * Complex.Gamma (s / 2) = Complex.Gammaℝ s from
    (Complex.Gammaℝ_def s).symm]
  rw [riemannZeta_def_of_ne_zero hs_ne]
  exact mul_div_cancel₀ _ hG

/-! ## Symmetry of completed zeta -/

/-- Λ(1-s) = Λ(s) in the critical strip (0 < Re(s) < 1).
    Both sides equal completedRiemannZeta, which satisfies the functional equation. -/
theorem LambdaV2_one_sub (s : ℂ) (hs0 : 0 < s.re) (hs1 : s.re < 1) :
    LambdaV2 (1 - s) = LambdaV2 s := by
  have h1s_re : 0 < (1 - s).re := by
    simp [Complex.sub_re, Complex.one_re]; linarith
  rw [LambdaV2_eq_completedZeta s hs0,
      LambdaV2_eq_completedZeta (1 - s) h1s_re,
      completedRiemannZeta_one_sub]

end
