/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
UUID: 7652b0c3-3116-4994-b9af-00fa6acbd108

Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Structure bundling assumptions about Hardy's Z function for use when
full proofs are not available.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators Real Nat Classical Pointwise
open Complex MeasureTheory Set Filter Topology Asymptotics

set_option maxHeartbeats 1600000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def riemannSiegelThetaAssump (t : ℝ) : ℝ :=
  (Complex.arg (Complex.Gamma (1/4 + I * t/2))) - t/2 * Real.log Real.pi

def hardyZAssump (t : ℝ) : ℝ :=
  (Complex.exp (I * riemannSiegelThetaAssump t) * riemannZeta (1/2 + I * t)).re

/-- Bundle of assumptions about Hardy's Z function.
    Use this when full proofs are not available. -/
structure HardyAssumptions where
  /-- Z(t) is real-valued -/
  hardyZ_real : ∀ t : ℝ, (Complex.exp (I * riemannSiegelThetaAssump t) *
    riemannZeta (1/2 + I * t)).im = 0
  /-- Z(t) is continuous -/
  hardyZ_continuous : Continuous hardyZAssump
  /-- Mean square asymptotic -/
  zeta_critical_line_mean_square :
    (fun T => ∫ t in (0)..T, Complex.normSq (riemannZeta (1/2 + I * t))) =Θ[atTop]
    (fun T => T * Real.log T)
  /-- Integral bound -/
  hardyZ_integral_bound : ∀ ε > 0,
    (fun T => ∫ t in (0)..T, hardyZAssump t) =O[atTop] (fun T => T^(1/2 + ε))
  /-- Convexity bound -/
  zeta_convexity_bound :
    (fun t : ℝ => riemannZeta (1/2 + I * t)) =O[atTop] (fun t => (t : ℂ)^(1/4 : ℂ))

end
