/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
UUID: 877c75a7-98b0-4659-9a92-087ac98709f7

Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Horizontal segment bounds for Perron's formula.

KEY RESULTS (PROVED):
- norm_integrand_le: |x^{σ+iT} / (σ+iT)| ≤ x^c / T on horizontal segment
- horizontal_segment_xpow_bound: ‖∫ x^s/s‖ ≤ c·x^c/T
- horizontal_segment_bound: ‖∫ x^s/s · (-ζ'/ζ)‖ ≤ O(x^c log²T / T)

These bounds show horizontal segment integrals vanish as T → ∞.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 1600000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Bound for the integrand on the horizontal segment.
-/
lemma norm_integrand_le (x : ℝ) (hx : 1 < x) (c : ℝ) (hc : 0 < c) (T : ℝ) (hT : 0 < T) (σ : ℝ) (hσ : σ ∈ Set.Icc 0 c) :
    ‖(x : ℂ)^(σ + Complex.I * T) / (σ + Complex.I * T)‖ ≤ x^c / T := by
      -- Since $x > 1$, we know that $\|x^{\sigma+iT}\| = x^\sigma$.
      have h_norm : ‖(x : ℂ) ^ (σ + Complex.I * T)‖ = x ^ σ := by
        norm_num [ Complex.norm_cpow_of_ne_zero, show x ≠ 0 by positivity ];
        norm_num [ abs_of_pos ( zero_lt_one.trans hx ), Complex.arg_ofReal_of_nonneg ( zero_le_one.trans hx.le ) ];
      simp +zetaDelta at *;
      gcongr ; aesop;
      exact Real.le_sqrt_of_sq_le ( by norm_num [ Complex.normSq ] ; nlinarith )

/-
Bound for the horizontal segment integral of x^s/s using the ML inequality.
-/
lemma horizontal_segment_xpow_bound (x : ℝ) (hx : 1 < x) (c : ℝ) (hc : 0 < c) (T : ℝ) (hT : 1 < T) :
    ‖∫ σ in (0:ℝ)..c, (x : ℂ)^(σ + Complex.I * T) / (σ + Complex.I * T)‖ ≤ c * (x^c / T) := by
      refine' le_trans ( intervalIntegral.norm_integral_le_of_norm_le_const _ ) _;
      exact x ^ c / T;
      · intro σ hσ;
        have := norm_integrand_le x hx c hc T ( by linarith ) σ ⟨ by cases Set.mem_uIoc.mp hσ <;> linarith, by cases Set.mem_uIoc.mp hσ <;> linarith ⟩ ; aesop;
      · norm_num [ abs_of_pos hc, mul_comm ]

/-
Bound for the horizontal segment integral involving ζ'/ζ, assuming a bound on ζ'/ζ.
-/
lemma horizontal_segment_bound (x : ℝ) (hx : 1 < x) (c : ℝ) (hc : 1 < c) (T : ℝ) (hT : 1 < T)
    (K : ℝ) (h_zeta : ∀ σ ∈ Set.Icc (-1) c, ‖deriv riemannZeta (σ + Complex.I * T) / riemannZeta (σ + Complex.I * T)‖ ≤ K * (Real.log T)^2) :
    ‖∫ σ in (-1:ℝ)..c, (x : ℂ)^(σ + Complex.I * T) / (σ + Complex.I * T) *
      (-deriv riemannZeta (σ + Complex.I * T) / riemannZeta (σ + Complex.I * T))‖
    ≤ (K * (c + 1)) * x^c * (Real.log T)^2 / T := by
      field_simp;
      refine' le_trans ( mul_le_mul_of_nonneg_right ( intervalIntegral.norm_integral_le_of_norm_le_const _ ) ( by positivity ) ) _;
      exact ( x ^ c / T ) * ( K * Real.log T ^ 2 );
      · intro σ hσ; specialize h_zeta σ ⟨ by cases Set.mem_uIoc.mp hσ <;> linarith, by cases Set.mem_uIoc.mp hσ <;> linarith ⟩ ; simp_all +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm ] ;
        -- We'll use the fact that $|x^{\sigma + iT}| = x^\sigma$ and $|\sigma + iT| \geq T$.
        have h_abs : ‖(x : ℂ)^(σ + Complex.I * T)‖ ≤ x^c ∧ ‖(σ : ℂ) + Complex.I * T‖ ≥ T := by
          rw [ Complex.norm_cpow_eq_rpow_re_of_pos ] <;> norm_num [ hx.le ];
          · exact ⟨ Real.rpow_le_rpow_of_exponent_le hx.le ( by cases Set.mem_uIoc.mp hσ <;> linarith ), Real.le_sqrt_of_sq_le ( by norm_num [ Complex.normSq ] ; nlinarith ) ⟩;
          · positivity;
        convert mul_le_mul ( inv_anti₀ ( by positivity ) h_abs.2 ) ( mul_le_mul h_zeta h_abs.1 ( by positivity ) ( by nlinarith [ show 0 ≤ K * Real.log T ^ 2 by exact le_trans ( by positivity ) h_zeta ] ) ) ( by positivity ) ( by positivity ) using 1 ; ring;
        ring;
      · rw [ abs_of_nonneg ( by linarith ) ] ; ring_nf; norm_num [ show T ≠ 0 by linarith ] ;

end
