/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
UUID: 1406cca8-2dbf-4573-ab0a-b29573e92d60

Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Integral formula for the real part of 1/(c + ti).

KEY RESULTS (PROVED):
- integral_real_part_arctan: ∫_{-R}^{R} Re(1/(c+ti)) dt = 2 arctan(R/c)

This is used in Perron's formula for computing contour integrals.
The key observation is that Re(1/(c+ti)) = c/(c² + t²), and the
antiderivative of 1/(c² + t²) is (1/c) arctan(t/c).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 1600000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-- The integral of the real part of 1/(c + ti) from -R to R is 2 * arctan(R/c).
    This is a key formula used in Perron's formula for summing Dirichlet series.
    Note: Re(1/(c + ti)) = c/(c² + t²), so we're computing ∫ c/(c² + t²) dt. -/
lemma integral_real_part_arctan (c : ℝ) (hc : 0 < c) (R : ℝ) (hR : 0 < R) :
    ∫ t in -R..R, (1 / (c + t * Complex.I)).re = 2 * Real.arctan (R / c) := by
      norm_num [ Complex.normSq, Complex.div_re ];
      rw [ intervalIntegral.integral_deriv_eq_sub' ];
      case f => exact fun t => Real.arctan ( t / c );
      · simpa [ neg_div ] using by ring;
      · -- By simplifying, we can see that the derivatives are equal.
        funext t;
        field_simp [hc];
        ring;
        rw [ show deriv ( fun t => Real.arctan ( t * c⁻¹ ) ) t = ( 1 + ( t * c⁻¹ ) ^ 2 ) ⁻¹ * c⁻¹ by norm_num [ Real.differentiableAt_arctan ] ] ; ring;
        field_simp;
      · norm_num;
      · exact continuousOn_of_forall_continuousAt fun t ht => ContinuousAt.div continuousAt_const ( Continuous.continuousAt ( by continuity ) ) ( by nlinarith )

end
