/-
Landau's Lemma - Generated by Aristotle (Harmonic)
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/
import Mathlib

set_option maxHeartbeats 400000

open scoped BigOperators Real Nat Classical Pointwise

noncomputable section

theorem partial_sums_mono {a : ℕ → ℝ} (ha : ∀ n, 0 ≤ a n) :
    Monotone (fun N => ∑ n ∈ Finset.range N, a n) :=
  fun n m hnm => Finset.sum_le_sum_of_subset_of_nonneg (Finset.range_mono hnm) fun _ _ _ => ha _

theorem tendsto_atTop_of_nonneg_not_summable
    {a : ℕ → ℝ} (ha : ∀ n, 0 ≤ a n) (hns : ¬ Summable a) :
    Filter.Tendsto (fun N => ∑ n ∈ Finset.range N, a n) Filter.atTop Filter.atTop :=
  not_summable_iff_tendsto_nat_atTop_of_nonneg ha |>.1 hns

theorem dirichlet_series_eq_tsum_real
    (a : ℕ → ℝ) (σ : ℝ)
    (hs : Summable (fun n => a n * (n : ℝ)^(-σ))) :
    (∑' n, (a n : ℂ) * (n : ℂ)^(-(σ : ℂ))).re = ∑' n, a n * (n : ℝ)^(-σ) := by
  sorry -- Aristotle proof needs exact? resolution

theorem analyticAt_bounded_on_compact
    {f : ℂ → ℂ} {z₀ : ℂ} (hf : AnalyticAt ℂ f z₀) :
    ∃ r > 0, ∃ M, ∀ z, ‖z - z₀‖ ≤ r → ‖f z‖ ≤ M := by
  obtain ⟨δ, hδ_pos, hδ⟩ : ∃ δ > 0, ∀ z, ‖z - z₀‖ < δ → ‖f z - f z₀‖ < 1 := by
    simpa using Metric.continuousAt_iff.mp hf.continuousAt 1 zero_lt_one
  exact ⟨δ / 2, half_pos hδ_pos, ‖f z₀‖ + 1, fun z hz => by
    linarith [norm_sub_norm_le (f z) (f z₀), hδ z (lt_of_le_of_lt hz (by linarith))]⟩

end
