/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f2e47fcd-f407-4617-b375-f8fb06e06b4e

Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Standalone file: Phragmen-Lindelof partial work.
NOT imported by any bridge — standalone reference material.
INCOMPLETE: Aristotle noted missing GammaGrowthBounds.lean and PhragmenLindelof.lean imports.

Contains (0 sorries):
- convexity_exponent: μ(σ) function definition
- chi: χ(s) factor in functional equation ζ(s) = χ(s)ζ(1-s)
- gamma_step_up: Γ(σ+1+it) = (σ+it)Γ(σ+it) (PROVED)
- complex_sin_growth: |sin(π(σ+it)/2)| ≤ C·e^(π|t|/2) (PROVED)
- phragmen_aux: auxiliary function for Phragmen-Lindelof
- Complex.abs: abbreviation for norm

NOTE: This is partial work. The full convexity bound requires importing
GammaGrowthBounds.lean (which exists in project) and assembling the pieces.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 1600000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

namespace Aristotle.PhragmenLindelofV3

/-
The convexity exponent for the Phragmén-Lindelöf bound of the Riemann zeta function. It is (1-2σ)/2 for σ ≤ 0, (1-σ)/2 for 0 < σ ≤ 1, and 0 for σ > 1.
-/
noncomputable def convexity_exponent (σ : ℝ) : ℝ :=
  if σ ≤ 0 then (1 - 2 * σ) / 2
  else if σ ≤ 1 then (1 - σ) / 2
  else 0

/-
The factor χ(s) in the functional equation ζ(s) = χ(s)ζ(1-s). Defined as 2^s * π^(s-1) * sin(πs/2) * Γ(1-s).
-/
noncomputable def chi (s : ℂ) : ℂ :=
  2 ^ s * (Real.pi : ℂ) ^ (s - 1) * Complex.sin (Real.pi * s / 2) * Complex.Gamma (1 - s)

/-
Functional equation for the Gamma function: Γ(s+1) = sΓ(s), applied to s = σ + it, valid for |t| ≥ 1.
-/
theorem gamma_step_up (σ t : ℝ) (ht : |t| ≥ 1) :
  Complex.Gamma (σ + 1 + t * Complex.I) = (σ + t * Complex.I) * Complex.Gamma (σ + t * Complex.I) := by
    by_cases h : ( σ : ℂ ) + t * Complex.I = 0 <;> simp_all +decide [ add_assoc, Complex.Gamma_add_one ];
    · simp_all +decide [ Complex.ext_iff ];
      linarith;
    · rw [ show ( σ : ℂ ) + ( 1 + t * Complex.I ) = ( σ + t * Complex.I ) + 1 by ring, Complex.Gamma_add_one ] ; aesop

/-
Growth bound for the complex sine function: |sin(π(σ+it)/2)| ≤ C * e^(π|t|/2) for |t| ≥ 1.
-/
theorem complex_sin_growth (σ : ℝ) : ∃ C > 0, ∀ t : ℝ, |t| ≥ 1 →
  ‖Complex.sin (Real.pi * (σ + t * Complex.I) / 2)‖ ≤ C * Real.exp (Real.pi * |t| / 2) := by
    -- The absolute value of the sine function is bounded by the exponential function.
    have h_sin_bound : ∀ z : ℂ, ‖Complex.sin z‖ ≤ Real.exp (‖z‖) := by
      intro z; rw [ Complex.sin ] ; norm_num [ Complex.norm_exp ] ; ring_nf; (
      refine' le_trans ( mul_le_mul_of_nonneg_right ( norm_sub_le _ _ ) ( by norm_num ) ) _ ; norm_num [ Complex.norm_exp ] ; ring_nf ;
      nlinarith [ Real.exp_pos z.im, Real.exp_pos ( -z.im ), Real.exp_le_exp.mpr ( show z.im ≤ ‖z‖ by exact le_trans ( Complex.im_le_norm _ ) ( by norm_num ) ), Real.exp_le_exp.mpr ( show -z.im ≤ ‖z‖ by exact le_trans ( neg_le_abs _ ) ( by simpa using Complex.abs_im_le_norm z ) ) ]);
    -- Apply the bound to |sin(π(σ+it)/2)| and simplify the expression.
    obtain ⟨C, hC⟩ : ∃ C > 0, ∀ t : ℝ, |t| ≥ 1 → Real.exp (‖(Real.pi * (σ + t * Complex.I)) / 2‖) ≤ C * Real.exp (Real.pi * |t| / 2) := by
      -- We'll use that ‖(π * (σ + t * Complex.I)) / 2‖ is bounded by π * |t| / 2 + π * |σ| / 2.
      have h_norm_bound : ∀ t : ℝ, |t| ≥ 1 → ‖(Real.pi * (σ + t * Complex.I)) / 2‖ ≤ Real.pi * |t| / 2 + Real.pi * |σ| / 2 := by
        norm_num [ Complex.norm_def, Complex.normSq ];
        intro t ht; rw [ abs_of_nonneg Real.pi_pos.le ] ; ring_nf; norm_num [ Real.sqrt_le_iff ] ; ring_nf ;
        nlinarith [ Real.pi_pos, show Real.sqrt ( σ ^ 2 + t ^ 2 ) ≤ |t| + |σ| by rw [ Real.sqrt_le_left ] <;> cases abs_cases t <;> cases abs_cases σ <;> nlinarith, abs_nonneg t, abs_nonneg σ ];
      exact ⟨ Real.exp ( Real.pi * |σ| / 2 ), Real.exp_pos _, fun t ht => by rw [ ← Real.exp_add ] ; exact Real.exp_le_exp.mpr ( by linarith [ h_norm_bound t ht ] ) ⟩;
    exact ⟨ C, hC.1, fun t ht => le_trans ( h_sin_bound _ ) ( hC.2 t ht ) ⟩

/-
Auxiliary function for Phragmén-Lindelöf proof. Designed to be bounded in the critical strip for t ≥ 1.
It effectively divides ζ(s) by the expected growth rate |t|^((1-σ)/2 + ε).
-/
noncomputable def phragmen_aux (s : ℂ) (ε : ℝ) : ℂ :=
  riemannZeta s * (s + 1) ^ (-(1 - s) / 2 - ε) * Complex.exp (-Complex.I * Real.pi * s / 4)

/-
Defining Complex.abs as an abbreviation for the norm, to match the user's notation.
-/
abbrev Complex.abs (z : ℂ) : ℝ := ‖z‖

end Aristotle.PhragmenLindelofV3
