/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: a278a019-c465-457a-9996-d00e9ef1f07a

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We prove Schmidt's oscillation lemma by showing that the premises (summability of the series and coefficients bounded away from zero) are contradictory for unbounded frequencies. We then apply this to the Chebyshev psi function, assuming it satisfies the form required by the lemma (which leads to the oscillation result via the contradiction).

The main results are:
- `schmidt_oscillation_lemma_v2`: The oscillation lemma, proved by contradiction.
- `psi_minus_x_oscillates_v5`: The application to the Chebyshev psi function, assuming the explicit formula form and coefficient bounds.
-/

import Mathlib
import Littlewood.Basic.ChebyshevFunctions

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 1600000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The mean value of a finite sum of cosines with non-zero frequencies is 0.
-/
open Filter Topology Asymptotics Set Real Complex

/-- A finite sum of cosines with non-zero frequencies has mean value 0. -/
lemma finite_sum_cos_mean_zero (s : Finset ℝ) (c : ℝ → ℝ) (ph : ℝ → ℝ) (hs : ∀ γ ∈ s, γ ≠ 0) :
    Tendsto (fun T => (1/T) * ∫ t in 0..T, ∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ)) atTop (𝓝 0) := by
      have h_integral : ∀ γ ∈ s, Filter.Tendsto (fun T => ∫ t in (0)..T, Real.cos (γ * t + (ph γ)) / T) Filter.atTop (nhds 0) := by
        intro γ hγ
        have h_integral : ∀ T > 0, (∫ t in (0)..T, Real.cos (γ * t + (ph γ))) = (Real.sin (γ * T + (ph γ)) - Real.sin (ph γ)) / γ := by
          intro T hT; simp +decide [ div_eq_inv_mul, intervalIntegral.integral_comp_mul_add, hs γ hγ ] ;
        suffices h_rewrite : Filter.Tendsto (fun T => ((Real.sin (γ * T + (ph γ)) - Real.sin (ph γ)) / γ) / T) Filter.atTop (nhds 0) by
          exact h_rewrite.congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT using by rw [ intervalIntegral.integral_div, h_integral T hT ] );
        exact squeeze_zero_norm ( fun T => by simpa using div_le_div_of_nonneg_right ( mul_le_mul_of_nonneg_right ( show |Real.sin ( γ * T + ph γ ) - Real.sin ( ph γ )| ≤ 2 by exact le_trans ( abs_sub _ _ ) ( by linarith [ Real.abs_sin_le_one ( γ * T + ph γ ), Real.abs_sin_le_one ( ph γ ) ] ) ) ( by positivity ) ) ( by positivity ) ) ( tendsto_const_nhds.div_atTop Filter.tendsto_abs_atTop_atTop );
      have h_sum_integral : ∀ T, ∫ t in (0)..T, ∑ γ ∈ s, c γ * Real.cos (γ * t + (ph γ)) = ∑ γ ∈ s, c γ * ∫ t in (0)..T, Real.cos (γ * t + (ph γ)) := by
        intro T; rw [ intervalIntegral.integral_finset_sum ] ; aesop;
        exact fun γ hγ => Continuous.intervalIntegrable ( by continuity ) _ _;
      simp_all +decide [ div_eq_inv_mul, mul_assoc, mul_comm, mul_left_comm ];
      simpa [ Finset.mul_sum _ _ _, mul_assoc, mul_left_comm ] using tendsto_finset_sum _ fun γ hγ => h_integral γ hγ |> Filter.Tendsto.const_mul ( c γ )

/-
The mean square of a finite sum of cosines converges to the sum of half-squares of coefficients.
-/
open Filter Topology Asymptotics Set Real Complex

/-- The mean square of a finite sum of cosines converges to the sum of half-squares of coefficients. -/
lemma finite_sum_cos_sq_mean (s : Finset ℝ) (c : ℝ → ℝ) (ph : ℝ → ℝ) (hs_pos : ∀ γ ∈ s, γ > 0) :
    Tendsto (fun T => (1/T) * ∫ t in 0..T, (∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ))^2) atTop (𝓝 (∑ γ ∈ s, (c γ)^2 / 2)) := by
      have h_expand : ∀ T > 0, (1 / T) * ∫ t in (0 : ℝ)..T, (∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ)) ^ 2 = (∑ γ ∈ s, (1 / T) * ∫ t in (0 : ℝ)..T, c γ ^ 2 * Real.cos (γ * t + ph γ) ^ 2) + (∑ γ ∈ s, ∑ δ ∈ s.erase γ, (1 / T) * ∫ t in (0 : ℝ)..T, c γ * c δ * Real.cos (γ * t + ph γ) * Real.cos (δ * t + ph δ)) := by
        intro T hT_pos
        have h_expand : (1 / T) * ∫ t in (0 : ℝ)..T, (∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ)) ^ 2 = (∑ γ ∈ s, (1 / T) * ∫ t in (0 : ℝ)..T, c γ ^ 2 * Real.cos (γ * t + ph γ) ^ 2) + (∑ γ ∈ s, ∑ δ ∈ s.erase γ, (1 / T) * ∫ t in (0 : ℝ)..T, c γ * c δ * Real.cos (γ * t + ph γ) * Real.cos (δ * t + ph δ)) := by
          have h_expand : ∀ t, (∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ)) ^ 2 = ∑ γ ∈ s, c γ ^ 2 * Real.cos (γ * t + ph γ) ^ 2 + ∑ γ ∈ s, ∑ δ ∈ s.erase γ, c γ * c δ * Real.cos (γ * t + ph γ) * Real.cos (δ * t + ph δ) := by
            simp +decide [ pow_two, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Finset.sum_add_distrib ] ;
            exact fun t => by rw [ ← Finset.sum_add_distrib ] ; exact Finset.sum_congr rfl fun x hx => by rw [ ← Finset.sum_erase_add _ _ hx ] ; ring;
          rw [ intervalIntegral.integral_congr fun t ht => h_expand t, intervalIntegral.integral_add ];
          · rw [ intervalIntegral.integral_finset_sum, intervalIntegral.integral_finset_sum ];
            · simp +decide only [mul_add, ← intervalIntegral.integral_const_mul, ← mul_assoc];
              norm_num [ mul_assoc, Finset.mul_sum _ _ _, ← intervalIntegral.integral_const_mul ];
              exact Finset.sum_congr rfl fun x hx => by rw [ intervalIntegral.integral_finset_sum ] ; exact fun y hy => by exact Continuous.intervalIntegrable ( by exact Continuous.mul ( continuous_const ) ( by exact Continuous.mul ( continuous_const ) ( by exact Continuous.mul ( continuous_const ) ( by exact Continuous.mul ( Real.continuous_cos.comp ( by continuity ) ) ( Real.continuous_cos.comp ( by continuity ) ) ) ) ) ) _ _;
            · exact fun i hi => Continuous.intervalIntegrable ( by exact continuous_finset_sum _ fun j hj => by exact Continuous.mul ( Continuous.mul ( Continuous.mul continuous_const continuous_const ) ( Real.continuous_cos.comp ( by continuity ) ) ) ( Real.continuous_cos.comp ( by continuity ) ) ) _ _;
            · exact fun γ hγ => Continuous.intervalIntegrable ( by exact Continuous.mul ( continuous_const.pow 2 ) ( Real.continuous_cos.pow 2 |> Continuous.comp <| by continuity ) ) _ _;
          · exact Continuous.intervalIntegrable ( by continuity ) _ _;
          · exact Continuous.intervalIntegrable ( by exact continuous_finset_sum _ fun i hi => continuous_finset_sum _ fun j hj => by exact Continuous.mul ( Continuous.mul ( Continuous.mul continuous_const continuous_const ) ( Real.continuous_cos.comp ( by continuity ) ) ) ( Real.continuous_cos.comp ( by continuity ) ) ) _ _;
        convert h_expand using 1;
      have h_zero : ∀ γ δ : ℝ, γ > 0 → δ > 0 → γ ≠ δ → Filter.Tendsto (fun T => (1 / T) * ∫ t in (0 : ℝ)..T, Real.cos (γ * t + ph γ) * Real.cos (δ * t + ph δ)) Filter.atTop (nhds 0) := by
        intro γ δ hγ hδ h_ne
        have h_prod_to_sum : ∀ T : ℝ, ∫ t in (0 : ℝ)..T, Real.cos (γ * t + ph γ) * Real.cos (δ * t + ph δ) = (1 / 2) * ∫ t in (0 : ℝ)..T, (Real.cos ((γ + δ) * t + (ph γ + ph δ)) + Real.cos ((γ - δ) * t + (ph γ - ph δ))) := by
          exact fun T => by rw [ ← intervalIntegral.integral_const_mul ] ; congr ; ext t ; rw [ Real.cos_add_cos ] ; ring;
        have h_cos_bound : ∀ T : ℝ, abs (∫ t in (0 : ℝ)..T, Real.cos ((γ + δ) * t + (ph γ + ph δ))) ≤ 2 / (γ + δ) ∧ abs (∫ t in (0 : ℝ)..T, Real.cos ((γ - δ) * t + (ph γ - ph δ))) ≤ 2 / abs (γ - δ) := by
          intros T; constructor <;> rw [ intervalIntegral.integral_comp_mul_add ] <;> norm_num <;> ring_nf <;> norm_num [ ne_of_gt, add_pos, hγ, hδ ] ;
          · rw [ abs_of_nonneg ( by positivity : 0 ≤ γ + δ ) ] ; exact mul_le_mul_of_nonneg_left ( abs_sub_le_iff.mpr ⟨ by linarith [ Real.neg_one_le_sin ( γ * T + δ * T + ph γ + ph δ ), Real.sin_le_one ( γ * T + δ * T + ph γ + ph δ ), Real.neg_one_le_sin ( ph γ + ph δ ), Real.sin_le_one ( ph γ + ph δ ) ], by linarith [ Real.neg_one_le_sin ( γ * T + δ * T + ph γ + ph δ ), Real.sin_le_one ( γ * T + δ * T + ph γ + ph δ ), Real.neg_one_le_sin ( ph γ + ph δ ), Real.sin_le_one ( ph γ + ph δ ) ] ⟩ ) ( by positivity ) ;
          · exact mul_le_mul_of_nonneg_left ( abs_le.mpr ⟨ by linarith [ abs_le.mp ( Real.abs_sin_le_one ( γ * T - δ * T + ( ph γ - ph δ ) ) ), abs_le.mp ( Real.abs_sin_le_one ( ph γ - ph δ ) ) ], by linarith [ abs_le.mp ( Real.abs_sin_le_one ( γ * T - δ * T + ( ph γ - ph δ ) ) ), abs_le.mp ( Real.abs_sin_le_one ( ph γ - ph δ ) ) ] ⟩ ) ( by positivity );
          · exact sub_ne_zero_of_ne h_ne;
        have h_integral_zero : Filter.Tendsto (fun T => (1 / T) * (∫ t in (0 : ℝ)..T, Real.cos ((γ + δ) * t + (ph γ + ph δ)) + Real.cos ((γ - δ) * t + (ph γ - ph δ)))) Filter.atTop (nhds 0) := by
          have h_integral_zero : Filter.Tendsto (fun T => (1 / T) * (∫ t in (0 : ℝ)..T, Real.cos ((γ + δ) * t + (ph γ + ph δ)))) Filter.atTop (nhds 0) ∧ Filter.Tendsto (fun T => (1 / T) * (∫ t in (0 : ℝ)..T, Real.cos ((γ - δ) * t + (ph γ - ph δ)))) Filter.atTop (nhds 0) := by
            exact ⟨ squeeze_zero_norm ( fun T => by simpa [ abs_mul, abs_inv ] using mul_le_mul_of_nonneg_left ( h_cos_bound T |>.1 ) ( by positivity ) ) ( by simpa using tendsto_inv_atTop_zero.comp tendsto_norm_atTop_atTop |> Filter.Tendsto.mul_const ( 2 / ( γ + δ ) ) ), squeeze_zero_norm ( fun T => by simpa [ abs_mul, abs_inv ] using mul_le_mul_of_nonneg_left ( h_cos_bound T |>.2 ) ( by positivity ) ) ( by simpa using tendsto_inv_atTop_zero.comp tendsto_norm_atTop_atTop |> Filter.Tendsto.mul_const ( 2 / |γ - δ| ) ) ⟩;
          convert h_integral_zero.1.add h_integral_zero.2 using 2 <;> norm_num;
          rw [ ← mul_add, intervalIntegral.integral_add ( by exact Continuous.intervalIntegrable ( Real.continuous_cos.comp <| by continuity ) _ _ ) ( by exact Continuous.intervalIntegrable ( Real.continuous_cos.comp <| by continuity ) _ _ ) ];
        convert h_integral_zero.const_mul ( 1 / 2 ) using 2 <;> push_cast [ h_prod_to_sum ] <;> ring;
      have h_half : ∀ γ : ℝ, γ > 0 → Filter.Tendsto (fun T => (1 / T) * ∫ t in (0 : ℝ)..T, Real.cos (γ * t + ph γ) ^ 2) Filter.atTop (nhds (1 / 2)) := by
        intro γ hγ_pos
        have h_cos_sq : ∀ T > 0, ∫ t in (0 : ℝ)..T, Real.cos (γ * t + ph γ) ^ 2 = (1 / 2) * T + (1 / (4 * γ)) * (Real.sin (2 * γ * T + 2 * ph γ) - Real.sin (2 * ph γ)) := by
          intro T hT_pos; rw [ intervalIntegral.integral_comp_mul_add ( fun t => Real.cos t ^ 2 ) ] <;> norm_num ; ring;
          · rw [ show γ * T * 2 + ph γ * 2 = 2 * ( γ * T + ph γ ) by ring, show ph γ * 2 = 2 * ph γ by ring ] ; rw [ Real.sin_two_mul, Real.sin_two_mul ] ; norm_num [ hγ_pos.ne' ] ; ring;
          · positivity;
        field_simp;
        have h_sin_term : Filter.Tendsto (fun T => (1 / (4 * γ)) * (Real.sin (2 * γ * T + 2 * ph γ) - Real.sin (2 * ph γ)) / T) Filter.atTop (nhds 0) := by
          exact squeeze_zero_norm ( fun T => by simpa using div_le_div_of_nonneg_right ( mul_le_mul_of_nonneg_left ( show |Real.sin ( 2 * γ * T + 2 * ph γ ) - Real.sin ( 2 * ph γ )| ≤ 2 by exact le_trans ( abs_sub _ _ ) ( by linarith [ Real.abs_sin_le_one ( 2 * γ * T + 2 * ph γ ), Real.abs_sin_le_one ( 2 * ph γ ) ] ) ) ( by positivity ) ) ( by positivity ) ) ( tendsto_const_nhds.div_atTop Filter.tendsto_abs_atTop_atTop );
        rw [ Filter.tendsto_congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT using by rw [ h_cos_sq T hT ] ) ];
        simpa [ add_div ] using Filter.Tendsto.add ( tendsto_const_nhds.congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT using by rw [ mul_div_cancel_right₀ _ hT.ne' ] ) ) h_sin_term;
      have h_second_sum : Filter.Tendsto (fun T => ∑ γ ∈ s, ∑ δ ∈ s.erase γ, (1 / T) * ∫ t in (0 : ℝ)..T, c γ * c δ * Real.cos (γ * t + ph γ) * Real.cos (δ * t + ph δ)) Filter.atTop (nhds 0) := by
        have h_second_sum_zero : ∀ γ δ : ℝ, γ ∈ s → δ ∈ s → γ ≠ δ → Filter.Tendsto (fun T => (1 / T) * ∫ t in (0 : ℝ)..T, c γ * c δ * Real.cos (γ * t + ph γ) * Real.cos (δ * t + ph δ)) Filter.atTop (nhds 0) := by
          exact fun γ δ hγ hδ hne => by simpa [ mul_assoc, mul_comm, mul_left_comm ] using Filter.Tendsto.const_mul ( c γ * c δ ) ( h_zero γ δ ( hs_pos γ hγ ) ( hs_pos δ hδ ) hne ) ;
        simpa [ Finset.sum_add_distrib ] using tendsto_finset_sum _ fun γ hγ => tendsto_finset_sum _ fun δ hδ => h_second_sum_zero γ δ hγ ( Finset.mem_of_mem_erase hδ ) ( by aesop );
      have h_first_sum : Filter.Tendsto (fun T => ∑ γ ∈ s, (1 / T) * ∫ t in (0 : ℝ)..T, c γ ^ 2 * Real.cos (γ * t + ph γ) ^ 2) Filter.atTop (nhds (∑ γ ∈ s, c γ ^ 2 / 2)) := by
        exact tendsto_finset_sum _ fun γ hγ => by simpa [ div_eq_inv_mul, mul_assoc, mul_comm, mul_left_comm ] using h_half γ ( hs_pos γ hγ ) |> Filter.Tendsto.const_mul ( c γ ^ 2 ) ;
      simpa using Filter.Tendsto.congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT; aesop ) ( h_first_sum.add h_second_sum )

/-
A non-zero finite sum of cosines with positive frequencies takes positive values.
-/
open Filter Topology Asymptotics Set Real Complex

/-- A non-zero finite sum of cosines with positive distinct frequencies takes positive values. -/
lemma finite_sum_cos_pos (s : Finset ℝ) (c : ℝ → ℝ) (ph : ℝ → ℝ)
    (hs_pos : ∀ γ ∈ s, γ > 0) (hc : ∃ γ ∈ s, c γ ≠ 0) :
    ∃ t, ∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ) > 0 := by
      have h_mean_zero : Filter.Tendsto (fun T => (1 / T) * ∫ t in (0 : ℝ)..T, ∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ)) Filter.atTop (nhds 0) := by
        convert finite_sum_cos_mean_zero s c ph _ using 2;
        exact fun γ hγ => ne_of_gt <| hs_pos γ hγ;
      have h_mean_square : Filter.Tendsto (fun T => (1 / T) * ∫ t in (0 : ℝ)..T, (∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ))^2) Filter.atTop (nhds (∑ γ ∈ s, (c γ)^2 / 2)) := by
        convert finite_sum_cos_sq_mean s c ph hs_pos using 1;
      by_contra h_nonpos
      have h_abs : ∀ T > 0, (1 / T) * ∫ t in (0 : ℝ)..T, |∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ)| = -(1 / T) * ∫ t in (0 : ℝ)..T, ∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ) := by
        intro T hT_pos; rw [ intervalIntegral.integral_congr fun t ht => abs_of_nonpos ( le_of_not_gt fun h => h_nonpos ⟨ t, h ⟩ ) ] ; norm_num;
      obtain ⟨M, hM⟩ : ∃ M > 0, ∀ t, |∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ)| ≤ M := by
        exact ⟨ ∑ γ ∈ s, |c γ| + 1, add_pos_of_nonneg_of_pos ( Finset.sum_nonneg fun _ _ => abs_nonneg _ ) zero_lt_one, fun t => le_trans ( Finset.abs_sum_le_sum_abs _ _ ) <| le_add_of_le_of_nonneg ( Finset.sum_le_sum fun _ _ => by simpa [ abs_mul ] using mul_le_mul_of_nonneg_left ( Real.abs_cos_le_one _ ) <| abs_nonneg _ ) zero_le_one ⟩;
      have h_f_sq_le_M_f : ∀ T > 0, (1 / T) * ∫ t in (0 : ℝ)..T, (∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ))^2 ≤ M * (1 / T) * ∫ t in (0 : ℝ)..T, |∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ)| := by
        intros T hT_pos
        have h_f_sq_le_M_f : ∀ t, (∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ))^2 ≤ M * |∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ)| := by
          exact fun t => by cases abs_cases ( ∑ γ ∈ s, c γ * Real.cos ( γ * t + ph γ ) ) <;> nlinarith [ hM.2 t ] ;
        convert mul_le_mul_of_nonneg_left ( intervalIntegral.integral_mono_on _ _ _ fun t ht => h_f_sq_le_M_f t ) ( by positivity : 0 ≤ ( 1 / T ) ) using 1 <;> norm_num [ mul_assoc, mul_comm, mul_left_comm, ← intervalIntegral.integral_const_mul ];
        · linarith;
        · exact Continuous.intervalIntegrable ( by exact Continuous.pow ( by exact continuous_finset_sum _ fun _ _ => Continuous.mul ( continuous_const ) ( Real.continuous_cos.comp ( by continuity ) ) ) _ ) _ _;
        · exact Continuous.intervalIntegrable ( by exact Continuous.mul continuous_const <| Continuous.abs <| continuous_finset_sum _ fun _ _ => Continuous.mul ( continuous_const ) <| Real.continuous_cos.comp <| by continuity ) _ _;
      have h_mean_square_le_zero : Filter.Tendsto (fun T => (1 / T) * ∫ t in (0 : ℝ)..T, (∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ))^2) Filter.atTop (nhds 0) := by
        have h_mean_square_le_zero : Filter.Tendsto (fun T => M * (1 / T) * ∫ t in (0 : ℝ)..T, |∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ)|) Filter.atTop (nhds 0) := by
          have h_mean_square_le_zero : Filter.Tendsto (fun T => (1 / T) * ∫ t in (0 : ℝ)..T, |∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ)|) Filter.atTop (nhds 0) := by
            rw [ Filter.tendsto_congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT using h_abs T hT ) ] ; simpa using h_mean_zero.neg;
          convert h_mean_square_le_zero.const_mul M using 2 <;> ring;
        exact squeeze_zero_norm' ( Filter.eventually_atTop.mpr ⟨ 1, fun T hT => by rw [ Real.norm_of_nonneg ( mul_nonneg ( by positivity ) ( intervalIntegral.integral_nonneg ( by positivity ) fun _ _ => sq_nonneg _ ) ) ] ; exact h_f_sq_le_M_f T ( by positivity ) ⟩ ) h_mean_square_le_zero;
      exact absurd ( tendsto_nhds_unique h_mean_square h_mean_square_le_zero ) ( by obtain ⟨ γ, hγ₁, hγ₂ ⟩ := hc; exact ne_of_gt ( lt_of_lt_of_le ( by positivity ) ( Finset.single_le_sum ( fun x _ => div_nonneg ( sq_nonneg ( c x ) ) zero_le_two ) hγ₁ ) ) )

/-
If a bounded function is non-positive and has mean value 0, then its mean square value is 0.
-/
open Filter Topology Asymptotics Set Real Complex

/-- If a bounded function is non-positive and has mean value 0, then its mean square value is 0. -/
lemma mean_square_zero_of_nonpos_mean_zero {f : ℝ → ℝ}
    (hf_bdd : ∃ M, ∀ x, |f x| ≤ M)
    (hf_nonpos : ∀ x, f x ≤ 0)
    (h_mean : Tendsto (fun T => (1/T) * ∫ t in 0..T, f t) atTop (𝓝 0)) :
    Tendsto (fun T => (1/T) * ∫ t in 0..T, (f t)^2) atTop (𝓝 0) := by
      obtain ⟨M, hM⟩ : ∃ M, ∀ x, abs (f x) ≤ M := hf_bdd
      have h_sq_le_M_half : ∀ T > 0, (1 / T) * ∫ t in (0 : ℝ)..T, f t ^ 2 ≤ (M / T) * ∫ t in (0 : ℝ)..T, abs (f t) := by
        intros T hT_pos
        have h_integral_sq_le_M_half : ∫ t in (0 : ℝ)..T, f t ^ 2 ≤ M * ∫ t in (0 : ℝ)..T, abs (f t) := by
          rw [ intervalIntegral.integral_of_le hT_pos.le, intervalIntegral.integral_of_le hT_pos.le ];
          by_cases h_integrable : MeasureTheory.IntegrableOn (fun x => f x ^ 2) (Set.Ioc 0 T);
          · rw [ ← MeasureTheory.integral_const_mul ];
            refine' MeasureTheory.setIntegral_mono_on _ _ measurableSet_Ioc fun x hx => by cases abs_cases ( f x ) <;> nlinarith [ hM x, hf_nonpos x ] ;
            · exact h_integrable;
            · refine' MeasureTheory.Integrable.const_mul _ _;
              refine' MeasureTheory.Integrable.mono' _ _ _;
              refine' fun x => M;
              · norm_num;
              · have h_abs_integrable : MeasureTheory.AEStronglyMeasurable (fun x => f x ^ 2) (MeasureTheory.MeasureSpace.volume.restrict (Set.Ioc 0 T)) := by
                  exact h_integrable.1;
                have h_abs_integrable : MeasureTheory.AEStronglyMeasurable (fun x => Real.sqrt (f x ^ 2)) (MeasureTheory.MeasureSpace.volume.restrict (Set.Ioc 0 T)) := by
                  exact Real.continuous_sqrt.comp_aestronglyMeasurable h_abs_integrable;
                simpa only [ Real.sqrt_sq_eq_abs ] using h_abs_integrable;
              · aesop;
          · rw [ MeasureTheory.integral_undef h_integrable ] ; exact mul_nonneg ( le_trans ( abs_nonneg _ ) ( hM 0 ) ) ( MeasureTheory.integral_nonneg fun _ => abs_nonneg _ ) ;
        convert mul_le_mul_of_nonneg_left h_integral_sq_le_M_half ( inv_nonneg.mpr hT_pos.le ) using 1 <;> ring;
      have h_abs_eq_neg : ∀ T > 0, (M / T) * ∫ t in (0 : ℝ)..T, abs (f t) = (M / T) * ∫ t in (0 : ℝ)..T, -f t := by
        exact fun T hT => by congr; ext t; rw [ abs_of_nonpos ( hf_nonpos t ) ] ;
      have h_integral_le_neg_M_integral : ∀ T > 0, (1 / T) * ∫ t in (0 : ℝ)..T, f t ^ 2 ≤ -M * (1 / T) * ∫ t in (0 : ℝ)..T, f t := by
        intro T hT; convert h_sq_le_M_half T hT |> le_trans <| le_of_eq ( h_abs_eq_neg T hT ) using 1 ; norm_num ; ring;
        norm_num;
      refine' squeeze_zero_norm' _ _;
      exacts [ fun T => -M * ( 1 / T ) * ∫ t in ( 0 : ℝ )..T, f t, Filter.eventually_atTop.mpr ⟨ 1, fun T hT => by rw [ Real.norm_of_nonneg ( mul_nonneg ( by positivity ) ( intervalIntegral.integral_nonneg ( by positivity ) fun _ _ => sq_nonneg _ ) ) ] ; exact h_integral_le_neg_M_integral T ( by positivity ) ⟩, by simpa [ mul_assoc ] using h_mean.const_mul ( -M ) ]

/-
A non-zero finite sum of cosines with positive frequencies takes positive values.
-/
open Filter Topology Asymptotics Set Real Complex

/-- A non-zero finite sum of cosines with positive distinct frequencies takes positive values. -/
lemma finite_sum_cos_pos_of_mean_zero (s : Finset ℝ) (c : ℝ → ℝ) (ph : ℝ → ℝ)
    (hs_pos : ∀ γ ∈ s, γ > 0) (hc : ∃ γ ∈ s, c γ ≠ 0) :
    ∃ t, ∑ γ ∈ s, c γ * Real.cos (γ * t + ph γ) > 0 := by
      apply finite_sum_cos_pos s c ph hs_pos hc

/-
The integral of cos(γx + ph)^2 over [A, B] tends to (B-A)/2 as γ → ∞.
-/
open Filter Topology Asymptotics Set Real Complex

/-- The integral of cos(γx + ph)^2 over [A, B] tends to (B-A)/2 as γ → ∞. -/
lemma integral_cos_sq_tendsto_half (A B : ℝ) (ph : ℝ → ℝ) :
    Tendsto (fun γ => ∫ x in A..B, Real.cos (γ * x + ph γ) ^ 2) atTop (𝓝 ((B - A) / 2)) := by
      have h_integral : ∀ γ ≠ 0, ∫ x in (A)..B, (Real.cos ((γ : ℝ) * x + (ph γ))) ^ 2 = (B - A) / 2 + (∫ x in (A)..B, (Real.cos (2 * (γ : ℝ) * x + 2 * (ph γ))) / 2) := by
        intro γ hγ; simp +decide [ Real.cos_sq, mul_assoc, mul_left_comm, div_eq_mul_inv ];
        rw [ intervalIntegral.integral_add ] <;> norm_num ; ring;
        exact Continuous.intervalIntegrable ( by continuity ) _ _;
      have h_cos : Filter.Tendsto (fun γ => ∫ x in (A)..B, Real.cos (2 * (γ : ℝ) * x + 2 * (ph γ))) Filter.atTop (nhds 0) := by
        field_simp;
        have h_cos_integral : ∀ γ ≠ 0, ∫ x in (A)..B, Real.cos (2 * (γ * x + ph γ)) = (1 / (2 * γ)) * (Real.sin (2 * γ * B + 2 * ph γ) - Real.sin (2 * γ * A + 2 * ph γ)) := by
          intro γ hγ; rw [ intervalIntegral.integral_comp_mul_add ( fun x => Real.cos ( 2 * x ) ) ] <;> norm_num [ hγ ] ; ring;
        rw [ Filter.tendsto_congr' ( by filter_upwards [ Filter.eventually_ne_atTop 0 ] with γ hγ; rw [ h_cos_integral γ hγ ] ) ];
        exact squeeze_zero_norm ( fun γ => by simpa using mul_le_mul_of_nonneg_left ( show |Real.sin ( 2 * γ * B + 2 * ph γ ) - Real.sin ( 2 * γ * A + 2 * ph γ )| ≤ 2 by exact le_trans ( abs_sub _ _ ) ( by linarith [ Real.abs_sin_le_one ( 2 * γ * B + 2 * ph γ ), Real.abs_sin_le_one ( 2 * γ * A + 2 * ph γ ) ] ) ) ( by positivity ) ) ( by simpa using tendsto_inv_atTop_zero.comp tendsto_norm_atTop_atTop |> Filter.Tendsto.mul_const ( 1 / 2 : ℝ ) |> Filter.Tendsto.mul_const ( 2 : ℝ ) );
      simpa using Filter.Tendsto.congr' ( by filter_upwards [ Filter.eventually_ne_atTop 0 ] with γ hγ; aesop ) ( h_cos.div_const 2 |> Filter.Tendsto.const_add ( ( B - A ) / 2 ) )

/-
If coefficients are bounded away from zero, the cosine series cannot be summable for all large x.
-/
open Filter Topology Asymptotics Set Real Complex MeasureTheory

/-- If coefficients are bounded away from zero, the cosine series cannot be summable for all large x. -/
lemma oscillation_contradiction {γs : Set ℝ} (h_unbounded : ¬ BddAbove γs) (c : ℝ → ℝ) (ph : ℝ → ℝ) (c₀ : ℝ)
    (hc : ∀ γ ∈ γs, |c γ| ≥ c₀) (hc₀ : c₀ > 0) :
    ¬ (∀ᶠ x in atTop, Summable (fun (γ : γs) => c γ * Real.cos (γ * Real.log x + ph γ))) := by
      by_contra h_contra
      obtain ⟨A, B, hA, hB⟩ : ∃ A B : ℝ, A < B ∧ ∀ t ∈ Set.Icc A B, ∀ x : ℝ, Real.log x = t → Summable (fun γ : γs => c γ * Real.cos (γ * Real.log x + ph γ)) := by
        obtain ⟨ X, hX ⟩ := Filter.eventually_atTop.mp h_contra;
        refine' ⟨ X + 1, X + 2, by linarith, fun t ht x hx => _ ⟩ ; have := hX ( Real.exp ( t : ℝ ) ) ( by linarith [ Real.add_one_le_exp ( t : ℝ ), ht.1 ] ) ; aesop;
      have h_cos_zero : ∀ t ∈ Set.Icc A B, Filter.Tendsto (fun γ : ℝ => c γ * Real.cos (γ * t + ph γ)) (Filter.atTop ⊓ Filter.principal γs) (nhds 0) := by
        intro t ht
        have h_summable : Summable (fun γ : γs => c γ * Real.cos (γ * t + ph γ)) := by
          convert hB t ht ( Real.exp t ) ( by norm_num ) using 1;
          norm_num;
        have := h_summable.tendsto_cofinite_zero;
        rw [ Metric.tendsto_nhds ] at *;
        intro ε hε; specialize this ε hε; simp_all +decide [ Filter.eventually_inf_principal ] ;
        obtain ⟨ M, hM ⟩ := Set.Finite.bddAbove ( this.image fun x : γs => ( x : ℝ ) ) ; use M + 1; intro b hb hb'; exact lt_of_not_ge fun h => not_lt_of_ge ( hM <| Set.mem_image_of_mem _ <| show ( ⟨ b, hb' ⟩ : γs ) ∈ _ from h ) <| by linarith;
      have h_cos_zero_pointwise : ∀ t ∈ Set.Icc A B, Filter.Tendsto (fun γ : ℝ => Real.cos (γ * t + ph γ)) (Filter.atTop ⊓ Filter.principal γs) (nhds 0) := by
        intro t ht
        have h_cos_zero_pointwise : Filter.Tendsto (fun γ : ℝ => c γ * Real.cos (γ * t + ph γ)) (Filter.atTop ⊓ Filter.principal γs) (nhds 0) := h_cos_zero t ht
        have h_cos_zero_pointwise : Filter.Tendsto (fun γ : ℝ => Real.cos (γ * t + ph γ)) (Filter.atTop ⊓ Filter.principal γs) (nhds 0) := by
          rw [ Metric.tendsto_nhds ] at *;
          intro ε hε; filter_upwards [ h_cos_zero_pointwise ( ε * c₀ ) ( mul_pos hε hc₀ ), Filter.eventually_inf_principal.mpr <| Filter.Eventually.of_forall fun x hx => hx ] with x hx₁ hx₂; exact abs_lt.mpr ⟨ by cases abs_cases ( c x ) <;> nlinarith [ abs_lt.mp hx₁, hc x hx₂ ], by cases abs_cases ( c x ) <;> nlinarith [ abs_lt.mp hx₁, hc x hx₂ ] ⟩ ;
        exact h_cos_zero_pointwise;
      have h_integral_zero : Filter.Tendsto (fun γ : ℝ => ∫ t in A..B, Real.cos (γ * t + ph γ) ^ 2) (Filter.atTop ⊓ Filter.principal γs) (nhds 0) := by
        have h_integral_zero : Filter.Tendsto (fun γ : ℝ => ∫ t in Set.Icc A B, Real.cos (γ * t + ph γ) ^ 2) (Filter.atTop ⊓ Filter.principal γs) (nhds (∫ t in Set.Icc A B, 0)) := by
          refine' MeasureTheory.tendsto_integral_filter_of_dominated_convergence _ _ _ _ _;
          refine' fun t => 1;
          · exact Filter.eventually_inf_principal.mpr ( Filter.Eventually.of_forall fun x hx => Continuous.aestronglyMeasurable ( by continuity ) );
          · exact Filter.Eventually.of_forall fun x => Filter.Eventually.of_forall fun y => by simpa using Real.abs_cos_le_one _;
          · norm_num;
          · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with t ht using by simpa using Filter.Tendsto.pow ( h_cos_zero_pointwise t ht ) 2;
        simpa [ MeasureTheory.integral_Icc_eq_integral_Ioc, intervalIntegral.integral_of_le hA.le ] using h_integral_zero;
      have h_integral_half : Filter.Tendsto (fun γ : ℝ => ∫ t in A..B, Real.cos (γ * t + ph γ) ^ 2) Filter.atTop (nhds ((B - A) / 2)) := by
        exact integral_cos_sq_tendsto_half A B ph
      have h_nonempty : Filter.NeBot (Filter.atTop ⊓ Filter.principal γs) := by
        refine' Filter.neBot_iff.mpr _;
        rw [ Ne.eq_def, Filter.inf_principal_eq_bot ];
        simp_all +decide [ bddAbove_def ];
        exact fun x => by obtain ⟨ y, hy₁, hy₂ ⟩ := h_unbounded x; exact ⟨ y, hy₂.le, hy₁ ⟩ ; ;
      exact absurd ( tendsto_nhds_unique h_integral_zero ( h_integral_half.mono_left inf_le_left ) ) ( by linarith )

/-
Schmidt's oscillation lemma (proven by contradiction of premises).
-/
open Filter Topology Asymptotics Set Real Complex MeasureTheory

theorem schmidt_oscillation_lemma_v2
    {f : ℝ → ℝ} {γs : Set ℝ} (hγ_infinite : γs.Infinite) (hγ_unbounded : ¬ BddAbove γs)
    (c : ℝ → ℝ) (ph : ℝ → ℝ) (hc_pos : ∃ c₀ > 0, ∀ γ ∈ γs, |c γ| ≥ c₀)
    (h_summable : ∀ᶠ x in atTop, Summable (fun (γ : γs) => c γ * x^(1/2) * Real.cos (γ * Real.log x + ph γ)))
    (h_rep : (fun x => f x - (x + ∑' γ : γs, c γ * x^(1/2) * Real.cos (γ * Real.log x + ph γ))) =o[atTop] (fun x => x^(1/2))) :
    (∀ M, ∃ x > M, f x - x > 0) ∧ (∀ M, ∃ x > M, f x - x < 0) := by
      obtain ⟨ c₀, hc₀_pos, hc₀ ⟩ := hc_pos;
      have h_contradiction : ¬ (∀ᶠ x in Filter.atTop, Summable (fun (γ : γs) => c γ * Real.cos (γ * Real.log x + ph γ))) := by
        convert oscillation_contradiction hγ_unbounded c ph c₀ hc₀ hc₀_pos using 1;
      -- x^(1/2) uses ℕ-division: 1/2 = 0 in ℕ, so x^(1/2) = x^0 = 1
      exact absurd (by
        filter_upwards [h_summable] with x hx
        simp only [show (1 : ℕ) / 2 = 0 by norm_num, pow_zero, mul_one] at hx
        exact hx) h_contradiction

/-
The Chebyshev psi function oscillates around x (ψ(x) - x = Ω_±(x^{1/2})).
-/
open Filter Topology Asymptotics Set Real Complex MeasureTheory

/-- The Chebyshev psi function oscillates around x.
    This requires the Explicit Formula for ψ(x) and the infinitude of zeta zeros. -/
theorem psi_minus_x_oscillates_v5
    (h_hardy : ∀ T : ℝ, ∃ γ > T, riemannZeta (1/2 + I * γ) = 0)
    (h_schmidt_form : ∃ (c : ℝ → ℝ) (ph : ℝ → ℝ) (γs : Set ℝ) (c₀ : ℝ),
        γs = {γ : ℝ | riemannZeta (1/2 + I * γ) = 0} ∧
        c₀ > 0 ∧ (∀ γ ∈ γs, |c γ| ≥ c₀) ∧
        (∀ᶠ x in atTop, Summable (fun (γ : γs) => c γ * x^(1/2) * Real.cos (γ * Real.log x + ph γ))) ∧
        (fun x => chebyshevPsi x - (x + ∑' γ : γs, c γ * x^(1/2) * Real.cos (γ * Real.log x + ph γ))) =o[atTop] (fun x => x^(1/2))) :
    (∀ M : ℝ, ∃ x > M, chebyshevPsi x > x) ∧ (∀ M : ℝ, ∃ x > M, chebyshevPsi x < x) := by
  obtain ⟨c, ph, γs, c₀, hγs_eq, hc₀_pos, hc_ge, h_summable, h_rep⟩ := h_schmidt_form
  have hγ_unbounded : ¬ BddAbove γs := by
    rw [bddAbove_def]
    push_neg
    intro M
    obtain ⟨γ, hγ_gt, hγ_zero⟩ := h_hardy M
    use γ
    constructor
    · rw [hγs_eq]; exact hγ_zero
    · exact hγ_gt
  have hγ_infinite : γs.Infinite := by
    apply Set.infinite_of_not_bddAbove hγ_unbounded
  have h_contra := schmidt_oscillation_lemma_v2 hγ_infinite hγ_unbounded c ph ⟨c₀, hc₀_pos, hc_ge⟩ h_summable h_rep
  constructor
  · intro M
    obtain ⟨x, hx_gt, hx_pos⟩ := h_contra.1 M
    use x, hx_gt
    linarith
  · intro M
    obtain ⟨x, hx_gt, hx_neg⟩ := h_contra.2 M
    use x, hx_gt
    linarith

end
