/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 9dddd550-07bb-4dec-92a8-ace5acf75d70

Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.

Stirling formula infrastructure: Bernoulli polynomials B1, B2 and their properties.

KEY RESULTS:
- B2_continuous: B2 is continuous (despite fract being discontinuous at integers)
- deriv_B2: B2'(t) = 2·B1(t) at non-integer points
- B2_zero: B2(0) = 1/6
- B2_bounded: |B2(t)| ≤ C for all t
- integral_B1_eq_B2_sub_const: ∫₀ˣ B1(t) dt = B2(x)/2 - 1/12
- hasDerivWithinAt_B2_right: right derivative of B2

STATUS: 1 sorry (exact? budget reached in hasDerivWithinAt_B2_right)
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 800000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

namespace StirlingBernoulli

noncomputable def B2 (t : ℝ) : ℝ := (Int.fract t)^2 - Int.fract t + 1/6

noncomputable def stirling_remainder (s : ℂ) : ℂ :=
  1 / (12 * s) - ∫ t in Set.Ioi 0, (B2 t : ℂ) / (2 * (s + t)^2)

noncomputable def B1 (t : ℝ) : ℝ := Int.fract t - 1/2

open Complex Real MeasureTheory Set Filter Topology

theorem B2_continuous : Continuous B2 := by
  have h_cont : Continuous (fun t : ℝ => (Int.fract t)^2 - Int.fract t) := by
    refine' continuous_iff_continuousAt.mpr _;
    intro x;
    by_cases hx : x ∈ Set.range Int.cast;
    · obtain ⟨ n, rfl ⟩ := hx;
      have h_left : Filter.Tendsto (fun t : ℝ => (Int.fract t)^2 - Int.fract t) (nhdsWithin (n : ℝ) (Set.Iio (n : ℝ))) (nhds ((1 : ℝ)^2 - 1)) := by
        have h_left : ∀ᶠ t : ℝ in nhdsWithin (n : ℝ) (Set.Iio (n : ℝ)), Int.fract t = t - (n - 1) := by
          norm_num [ eventually_nhdsWithin_iff ];
          filter_upwards [ lt_mem_nhds ( show ( n : ℝ ) > n - 1 by norm_num ) ] with x hx₁ hx₂ using by linarith [ Int.fract_add_floor x, show ( Int.floor x : ℝ ) = n - 1 by exact_mod_cast Int.floor_eq_iff.mpr ⟨ by norm_num; linarith, by norm_num; linarith ⟩ ] ;
        rw [ Filter.tendsto_congr' ( by filter_upwards [ h_left ] with t ht; rw [ ht ] ) ] ; exact tendsto_nhdsWithin_of_tendsto_nhds ( Continuous.tendsto' ( by continuity ) _ _ <| by norm_num ) ;
      have h_right : Filter.Tendsto (fun t : ℝ => (Int.fract t)^2 - Int.fract t) (nhdsWithin (n : ℝ) (Set.Ioi (n : ℝ))) (nhds ((0 : ℝ)^2 - 0)) := by
        have h_right : ∀ᶠ t : ℝ in nhdsWithin (n : ℝ) (Set.Ioi (n : ℝ)), (Int.fract t)^2 - Int.fract t = (t - n)^2 - (t - n) := by
          filter_upwards [ Ioo_mem_nhdsGT ( show ( n : ℝ ) < n + 1 by norm_num ) ] with t ht using by norm_num [ show ⌊t⌋ = n by exact Int.floor_eq_iff.mpr ⟨ by linarith [ ht.1 ], by linarith [ ht.2 ] ⟩, Int.fract ] ; ;
        rw [ Filter.tendsto_congr' h_right ] ; exact Continuous.continuousWithinAt ( by continuity ) |> fun h => h.trans ( by norm_num ) ;
      refine' continuousAt_iff_continuous_left'_right'.mpr _;
      simp_all +decide [ ContinuousWithinAt ];
    · field_simp;
      refine' ContinuousAt.mul _ _;
      · refine' ContinuousAt.sub _ _;
        · exact continuousAt_id;
        · have h_floor_const : ∃ ε > 0, ∀ y, abs (y - x) < ε → ⌊y⌋ = ⌊x⌋ := by
            norm_num [ Int.floor_eq_iff ] at *;
            exact Metric.mem_nhds_iff.mp ( Ico_mem_nhds ( lt_of_le_of_ne ( Int.floor_le x ) ( by tauto ) ) ( Int.lt_floor_add_one x ) ) |> fun ⟨ ε, hε₁, hε₂ ⟩ => ⟨ ε, hε₁, fun y hy => hε₂ <| by simpa using hy ⟩;
          exact tendsto_const_nhds.congr' ( Filter.eventuallyEq_of_mem ( Metric.ball_mem_nhds _ h_floor_const.choose_spec.1 ) fun y hy => by rw [ h_floor_const.choose_spec.2 y hy ] );
      · refine' ContinuousAt.sub _ continuousAt_const;
        refine' ContinuousAt.sub _ _;
        · exact continuousAt_id;
        · have h_floor_const : ∃ ε > 0, ∀ y, abs (y - x) < ε → ⌊y⌋ = ⌊x⌋ := by
            norm_num [ Int.floor_eq_iff ] at *;
            exact Metric.mem_nhds_iff.mp ( Ico_mem_nhds ( lt_of_le_of_ne ( Int.floor_le x ) ( by tauto ) ) ( Int.lt_floor_add_one x ) ) |> fun ⟨ ε, hε₁, hε₂ ⟩ => ⟨ ε, hε₁, fun y hy => hε₂ <| by simpa using hy ⟩;
          exact tendsto_const_nhds.congr' ( by filter_upwards [ Metric.ball_mem_nhds x h_floor_const.choose_spec.1 ] with y hy; rw [ h_floor_const.choose_spec.2 y hy ] );
  exact h_cont.add continuous_const

theorem deriv_B2 (t : ℝ) (ht : ¬ ∃ n : ℤ, t = n) :
    deriv B2 t = 2 * B1 t := by
  have h_deriv : deriv (fun t => (Int.fract t)^2 - Int.fract t + 1 / 6) t = 2 * (Int.fract t) * (deriv (fun t => Int.fract t) t) - (deriv (fun t => Int.fract t) t) := by
    have h_fract_diff : DifferentiableAt ℝ (fun t => Int.fract t) t := by
      obtain ⟨n, hn⟩ : ∃ n : ℤ, (n : ℝ) < t ∧ t < (n + 1 : ℝ) := by
        exact ⟨ ⌊t⌋, lt_of_le_of_ne ( Int.floor_le t ) fun h => ht ⟨ _, h.symm ⟩, Int.lt_floor_add_one t ⟩;
      refine' DifferentiableAt.congr_of_eventuallyEq _ _;
      exacts [ fun x => x - ↑n, differentiableAt_id.sub_const _, Filter.eventuallyEq_of_mem ( Ioo_mem_nhds hn.1 hn.2 ) fun x hx => by simp +decide [ show ⌊x⌋ = n by exact Int.floor_eq_iff.mpr ⟨ by linarith [ hx.1 ], by linarith [ hx.2 ] ⟩, Int.fract ] ];
    norm_num [ h_fract_diff ];
  have h_deriv_fract : deriv (fun t : ℝ => Int.fract t) t = 1 := by
    refine' HasDerivAt.deriv _;
    convert HasDerivAt.congr_of_eventuallyEq ( hasDerivAt_id t |> HasDerivAt.sub <| hasDerivAt_const _ _ ) ?_ using 1 ; aesop;
    exacts [ ↑⌊t⌋, Filter.eventuallyEq_of_mem ( Ioo_mem_nhds ( show ( ⌊t⌋ : ℝ ) < t from lt_of_le_of_ne ( Int.floor_le t ) fun h => ht ⟨ _, h.symm ⟩ ) ( show t < ( ⌊t⌋ + 1 : ℝ ) from Int.lt_floor_add_one t ) ) fun x hx => by simp +decide [ show ⌊x⌋ = ⌊t⌋ from Int.floor_eq_iff.mpr ⟨ by linarith [ hx.1, Int.floor_le t ], by linarith [ hx.2, Int.lt_floor_add_one t ] ⟩, Int.fract ] ];
  convert h_deriv using 1 ; norm_num [ h_deriv_fract, B1 ] ; ring

theorem B2_zero : B2 0 = 1/6 := by
  simp [B2]

theorem B2_bounded : ∃ C, ∀ t, |B2 t| ≤ C := by
  use 1 / 6 + 1 / 4 + 1 / 6
  intro t
  simp [B2];
  have h_fract_bounds : 0 ≤ Int.fract t ∧ Int.fract t < 1 := by
    apply And.intro; exact Int.fract_nonneg t; exact Int.fract_lt_one t
  norm_num [ abs_le ]
  constructor <;> nlinarith [ sq_nonneg ( Int.fract t - 1 / 2 ) ]

theorem integral_B1_eq_B2_sub_const (x : ℝ) :
    ∫ t in (0)..x, B1 t = B2 x / 2 - 1/12 := by
  unfold B1 B2;
  have h_B1 : ∀ n : ℤ, ∫ t in (n : ℝ)..((n + 1) : ℝ), Int.fract t - 1 / 2 = 0 := by
    intro n
    have : ∫ t in (n : ℝ)..((n + 1) : ℝ), Int.fract t - 1 / 2 = ∫ t in (n : ℝ)..((n + 1) : ℝ), t - n - 1 / 2 := by
      rw [ intervalIntegral.integral_of_le, intervalIntegral.integral_of_le ] <;> norm_num;
      norm_num [ MeasureTheory.integral_Ioc_eq_integral_Ioo ];
      exact MeasureTheory.setIntegral_congr_fun measurableSet_Ioo fun x hx => by simp +decide [ show ⌊x⌋ = n by exact Int.floor_eq_iff.mpr ⟨ hx.1.le, hx.2 ⟩, Int.fract ] ;
    norm_num [ this ];
    ring;
  have h_split : ∫ t in (0 : ℝ)..x, Int.fract t - 1 / 2 = (∫ t in (0 : ℝ)..(Int.floor x), Int.fract t - 1 / 2) + (∫ t in (Int.floor x)..x, Int.fract t - 1 / 2) := by
    rw [ intervalIntegral.integral_add_adjacent_intervals ] <;> apply_rules [ MeasureTheory.IntegrableOn.intervalIntegrable ];
    · refine' MeasureTheory.Integrable.mono' _ _ _;
      exacts [ fun t => 1, Continuous.integrableOn_Icc <| by continuity, Measurable.aestronglyMeasurable <| by exact Measurable.sub ( measurable_fract ) measurable_const, Filter.Eventually.of_forall fun t => abs_le.mpr ⟨ by linarith [ Int.fract_nonneg t ], by linarith [ Int.fract_lt_one t ] ⟩ ];
    · refine' MeasureTheory.Integrable.mono' _ _ _;
      exacts [ fun t => 1, Continuous.integrableOn_Icc <| by continuity, Measurable.aestronglyMeasurable <| by exact Measurable.sub ( measurable_fract ) measurable_const, Filter.Eventually.of_forall fun t => abs_le.mpr ⟨ by linarith [ Int.fract_nonneg t ], by linarith [ Int.fract_lt_one t ] ⟩ ];
  -- Integrability: fract t - 1/2 is bounded by 1 and measurable
  have h_intble : ∀ a b : ℝ, IntervalIntegrable (fun t => Int.fract t - 1 / 2) volume a b := by
    intro a b
    apply MeasureTheory.IntegrableOn.intervalIntegrable
    apply Measure.integrableOn_of_bounded
    · rw [Real.volume_interval]; exact ENNReal.ofReal_ne_top
    · exact (measurable_fract.sub measurable_const).aestronglyMeasurable
    · exact ae_of_all _ fun t => by
        rw [Real.norm_eq_abs]
        exact abs_le.mpr ⟨by linarith [Int.fract_nonneg t], by linarith [Int.fract_lt_one t]⟩
  have h_floor : ∫ t in (0 : ℝ)..(Int.floor x), Int.fract t - 1 / 2 = 0 := by
    -- Each unit interval integral is 0. Decompose by Nat induction.
    -- Note: Lean elaborates 1/2 as 2⁻¹ in some contexts, so we use norm_num to unify.
    have h_nat : ∀ m : ℕ, ∫ t in (0 : ℝ)..(m : ℝ), Int.fract t - 1 / 2 = 0 := by
      intro m; induction m with
      | zero => norm_num
      | succ m ih =>
        have hsplit : ∫ t in (0 : ℝ)..(↑(m + 1) : ℝ), Int.fract t - 1 / 2 =
            (∫ t in (0 : ℝ)..(m : ℝ), Int.fract t - 1 / 2) +
            ∫ t in (m : ℝ)..(↑(m + 1) : ℝ), Int.fract t - 1 / 2 := by
          rw [show (↑(m + 1) : ℝ) = (↑m : ℝ) + 1 from by push_cast; ring]
          exact (intervalIntegral.integral_add_adjacent_intervals (h_intble _ _) (h_intble _ _)).symm
        rw [hsplit, ih, zero_add]
        convert h_B1 (m : ℤ) using 2; push_cast; ring
    have h_neg : ∀ m : ℕ, ∫ t in (-(m : ℝ))..(0 : ℝ), Int.fract t - 1 / 2 = 0 := by
      intro m; induction m with
      | zero => norm_num
      | succ m ih =>
        have hsplit : ∫ t in (-(↑(m + 1) : ℝ))..(0 : ℝ), Int.fract t - 1 / 2 =
            (∫ t in (-(↑(m + 1) : ℝ))..(-(↑m : ℝ)), Int.fract t - 1 / 2) +
            ∫ t in (-(↑m : ℝ))..(0 : ℝ), Int.fract t - 1 / 2 := by
          exact (intervalIntegral.integral_add_adjacent_intervals (h_intble _ _) (h_intble _ _)).symm
        rw [hsplit, ih, add_zero]
        have : ∫ t in (-(↑(m + 1) : ℝ))..(-(↑m : ℝ)), Int.fract t - 1 / 2 =
               ∫ t in ((-(m + 1 : ℤ) : ℤ) : ℝ)..((-(m + 1 : ℤ) : ℤ) : ℝ) + 1, Int.fract t - 1 / 2 := by
          congr 1 <;> push_cast <;> ring
        rw [this]; exact h_B1 _
    by_cases h_nn : 0 ≤ ⌊x⌋
    · have hcast : (⌊x⌋ : ℝ) = ((⌊x⌋.toNat : ℕ) : ℝ) := by
        exact_mod_cast (Int.toNat_of_nonneg h_nn).symm
      rw [hcast]; exact h_nat _
    · push_neg at h_nn
      rw [intervalIntegral.integral_symm]
      have : ∫ t in (⌊x⌋ : ℝ)..(0 : ℝ), Int.fract t - 1 / 2 = 0 := by
        have hcast : (⌊x⌋ : ℝ) = -(((-⌊x⌋).toNat : ℕ) : ℝ) := by
          have h1 : ((-⌊x⌋).toNat : ℤ) = -⌊x⌋ := Int.toNat_of_nonneg (by omega)
          exact_mod_cast show (⌊x⌋ : ℤ) = -((-⌊x⌋).toNat : ℤ) by omega
        rw [hcast]; exact h_neg _
      linarith
  have h_frac : ∫ t in (Int.floor x)..x, Int.fract t - 1 / 2 = ∫ t in (Int.floor x)..x, (t - Int.floor x - 1 / 2) := by
    field_simp;
    rw [ intervalIntegral.integral_of_le ( Int.floor_le x ), intervalIntegral.integral_of_le ( Int.floor_le x ) ];
    exact MeasureTheory.setIntegral_congr_fun measurableSet_Ioc fun t ht => by rw [ Int.fract ] ; rw [ show ⌊t⌋ = ⌊x⌋ from Int.floor_eq_iff.mpr ⟨ by linarith [ ht.1, Int.floor_le x ], by linarith [ ht.2, Int.lt_floor_add_one x ] ⟩ ] ; ring;
  norm_num [ h_split, h_floor, h_frac ] ; ring;
  rw [ Int.fract ] ; ring

theorem hasDerivWithinAt_B2_right (t : ℝ) :
    HasDerivWithinAt B2 (2 * B1 t) (Set.Ioi t) t := by
  by_cases h : ∃ n : ℤ, t = n;
  · have h_cont : Filter.Tendsto (fun h => (B2 (t + h) - B2 t) / h) (nhdsWithin 0 (Set.Ioi 0)) (nhds (2 * B1 t)) := by
      have h_cont : Filter.Tendsto (fun h => (B2 (t + h) - B2 t) / h) (nhdsWithin 0 (Set.Ioi 0)) (nhds (2 * B1 t)) := by
        have h_lim : Filter.Tendsto (fun h => (B2 (t + h) - B2 t) / h) (nhdsWithin 0 (Set.Ioi 0)) (nhds (2 * (t - ⌊t⌋ - 1/2))) := by
          have h_cont : Filter.Tendsto (fun h => (B2 (t + h) - B2 t) / h) (nhdsWithin 0 (Set.Ioi 0)) (nhds (2 * (t + 0 - ⌊t + 0⌋ - 1/2))) := by
            have h_eq : ∀ᶠ h in nhdsWithin 0 (Set.Ioi 0), B2 (t + h) = (h - 0)^2 - (h - 0) + 1/6 := by
              obtain ⟨ n, rfl ⟩ := h; norm_num [ B2 ] ;
              filter_upwards [ Ioo_mem_nhdsGT zero_lt_one ] with x hx using by rw [ Int.fract ] ; norm_num [ show ⌊x⌋ = 0 from Int.floor_eq_iff.mpr ⟨ by norm_num; linarith [ hx.1 ], by norm_num; linarith [ hx.2 ] ⟩ ] ;
            have h_eq : ∀ᶠ h in nhdsWithin 0 (Set.Ioi 0), (B2 (t + h) - B2 t) / h = (h - 1) := by
              filter_upwards [ h_eq, self_mem_nhdsWithin ] with x hx hx' using by rw [ div_eq_iff hx'.out.ne' ] ; rw [ hx ] ; rw [ show B2 t = 1 / 6 by exact h.elim fun n hn => by simp +decide [ hn, B2 ] ] ; ring;;
            rw [ Filter.tendsto_congr' h_eq ] ; norm_num [ h ];
            exact tendsto_nhdsWithin_of_tendsto_nhds ( Continuous.tendsto' ( by continuity ) _ _ ( by norm_num [ show Int.fract t = 0 by obtain ⟨ n, rfl ⟩ := h; norm_num ] ) );
          aesop
        have : (2 : ℝ) * B1 t = 2 * (t - ↑⌊t⌋ - 1 / 2) := by unfold B1; rw [Int.fract]
        rw [this]; exact h_lim
      convert h_cont using 1;
    rw [ hasDerivWithinAt_iff_tendsto_slope ];
    convert h_cont.comp ( show Filter.Tendsto ( fun x : ℝ => x - t ) ( 𝓝[Set.Ioi t \ { t }] t ) ( 𝓝[>] 0 ) from ?_ ) using 2;
    · ext; simp +decide [ slope_def_field ];
    · rw [ Metric.tendsto_nhdsWithin_nhdsWithin ] ; aesop;
  · convert HasDerivAt.hasDerivWithinAt ( deriv_B2 t h ▸ hasDerivAt_deriv_iff.mpr _ ) using 1;
    refine' DifferentiableAt.congr_of_eventuallyEq _ _;
    exact fun x => ( x - ⌊x⌋ ) ^ 2 - ( x - ⌊x⌋ ) + 1 / 6;
    · obtain ⟨ε, hε⟩ : ∃ ε > 0, ∀ x, abs (x - t) < ε → ⌊x⌋ = ⌊t⌋ := by
        norm_num [ Int.floor_eq_iff ] at *;
        exact Metric.mem_nhds_iff.mp ( Ico_mem_nhds ( lt_of_le_of_ne ( Int.floor_le t ) ( Ne.symm ( h _ ) ) ) ( Int.lt_floor_add_one t ) ) |> fun ⟨ ε, ε_pos, hε ⟩ => ⟨ ε, ε_pos, fun x hx => hε hx ⟩;
      exact DifferentiableAt.congr_of_eventuallyEq ( show DifferentiableAt ℝ ( fun x => ( x - ( ⌊t⌋ : ℝ ) ) ^ 2 - ( x - ( ⌊t⌋ : ℝ ) ) + 1 / 6 ) t from by norm_num ) ( Filter.eventuallyEq_of_mem ( Metric.ball_mem_nhds t hε.1 ) fun x hx => by rw [ hε.2 x hx ] );
    · filter_upwards [ IsOpen.mem_nhds ( isOpen_compl_singleton.preimage continuous_id' ) ( show t ≠ ⌊t⌋ from fun h' => h ⟨ _, h' ⟩ ) ] with x hx using by unfold B2; aesop;

end StirlingBernoulli
