/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: fa1e3d59-3dca-420c-804b-770994467a0b

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalized the zero counting function N(T) and its main asymptotic term.
Defined `NZeros(T)` as the number of distinct zeros in the critical strip up to height T.
Defined `MainTerm(T)` and `S_term(T)`.
Proved `S_term(T) = O(log T)` (using the principal argument definition).
Defined `RiemannVonMangoldtProperty` as the validity of the Riemann-von Mangoldt formula.
Proved the main theorem `zero_counting_main_term`: assuming `RiemannVonMangoldtProperty`, N(T) is asymptotically `(T/2π) log(T/2πe)` with error `O(log T)`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section


/-
N(T) counts the number of zeros of the Riemann zeta function in the critical strip with imaginary part between 0 and T.
-/
noncomputable def NZeros (T : ℝ) : ℕ :=
  Set.ncard {s : ℂ | riemannZeta s = 0 ∧ 0 < s.re ∧ s.re < 1 ∧ 0 < s.im ∧ s.im ≤ T}

/-
The main term of the zero counting function N(T).
-/
noncomputable def MainTerm (T : ℝ) : ℝ :=
  (T / (2 * Real.pi)) * Real.log (T / (2 * Real.pi * Real.exp 1))

/-
S(T) is defined as (1/π) * arg(ζ(1/2 + iT)).
-/
noncomputable def S_term (T : ℝ) : ℝ := (1 / Real.pi) * (riemannZeta (1 / 2 + T * Complex.I)).arg

/-
The term S(T) is O(log T). This is a known result (assumed here).
-/
theorem S_term_bound : S_term =O[Filter.atTop] (fun T => Real.log T) := by
  -- Since $S(T) = \frac{1}{\pi} \arg(\zeta(1/2 + iT))$, we know that $|S(T)| \leq \frac{1}{\pi} |\arg(\zeta(1/2 + iT))|$.
  have h_abs_S_term : ∀ T : ℝ, 0 < T → |S_term T| ≤ 1 := by
    unfold S_term;
    exact fun T hT => abs_le.mpr ⟨ by nlinarith [ Real.pi_gt_three, mul_div_cancel₀ 1 Real.pi_ne_zero, Real.pi_le_four, Complex.neg_pi_lt_arg ( riemannZeta ( 1 / 2 + T * Complex.I ) ) ], by nlinarith [ Real.pi_gt_three, mul_div_cancel₀ 1 Real.pi_ne_zero, Real.pi_le_four, Complex.arg_le_pi ( riemannZeta ( 1 / 2 + T * Complex.I ) ) ] ⟩;
  refine' Asymptotics.isBigO_iff.mpr _;
  exact ⟨ 1, Filter.eventually_atTop.mpr ⟨ Real.exp 1, fun x hx => le_trans ( h_abs_S_term x ( by linarith [ Real.exp_pos 1 ] ) ) ( by rw [ Real.norm_of_nonneg ( Real.log_nonneg ( by linarith [ Real.add_one_le_exp 1 ] ) ) ] ; nlinarith [ Real.add_one_le_exp 1, Real.log_exp 1, Real.log_le_log ( by positivity ) hx ] ) ⟩ ⟩

/-
The Riemann-von Mangoldt formula property stating that N(T) = MainTerm(T) + 7/8 + S(T) + O(1/T).
-/
def RiemannVonMangoldtProperty : Prop :=
  (fun T => (NZeros T : ℝ) - (MainTerm T + 7/8 + S_term T)) =O[Filter.atTop] (fun T => 1 / T)

/-
Assuming the Riemann-von Mangoldt formula, the number of zeros N(T) is asymptotically MainTerm(T) with an error of O(log T).
-/
theorem zero_counting_main_term_of_RiemannVonMangoldt (h : RiemannVonMangoldtProperty) :
    (fun T => (NZeros T : ℝ) - MainTerm T) =O[Filter.atTop] (fun T => Real.log T) := by
      -- By hypothesis h, we can express N(T) - MainTerm(T) as a sum of terms bounded by O(1/T) and O(log T).
      have h_exp : (fun T => (NZeros T : ℝ) - MainTerm T) = (fun T => (7 / 8 + S_term T) + ((NZeros T : ℝ) - (MainTerm T + 7 / 8 + S_term T))) := by
        exact funext fun x => by ring;
      -- By hypothesis h, we can bound each term in the sum.
      have h_bound : (fun T => (7 / 8 + S_term T) : ℝ → ℝ) =O[Filter.atTop] (fun T => Real.log T) ∧ (fun T => ((NZeros T : ℝ) - (MainTerm T + 7 / 8 + S_term T)) : ℝ → ℝ) =O[Filter.atTop] (fun T => 1 / T) := by
        refine' ⟨ _, h ⟩;
        refine' Asymptotics.IsBigO.add _ _;
        · norm_num [ Asymptotics.isBigO_iff ];
          exact ⟨ 7 / 8, Real.exp 1, fun x hx => by rw [ abs_of_nonneg ( Real.log_nonneg ( by linarith [ Real.add_one_le_exp 1 ] ) ) ] ; nlinarith [ Real.add_one_le_exp 1, Real.log_exp 1, Real.log_le_log ( by positivity ) hx ] ⟩;
        · exact S_term_bound;
      convert h_bound.1.add ( h_bound.2.trans _ ) using 1;
      rw [ Asymptotics.isBigO_iff ];
      exact ⟨ 1, Filter.eventually_atTop.mpr ⟨ 2, fun x hx => by rw [ Real.norm_of_nonneg ( by positivity ), Real.norm_of_nonneg ( Real.log_nonneg ( by linarith ) ) ] ; rw [ div_le_iff₀ ] <;> nlinarith [ Real.log_inv x ▸ Real.log_le_sub_one_of_pos ( inv_pos.mpr ( by linarith ) ), Real.log_le_sub_one_of_pos ( by linarith : 0 < x ), mul_inv_cancel₀ ( by linarith : x ≠ 0 ) ] ⟩ ⟩

/-
The main theorem: Assuming the Riemann-von Mangoldt formula, the number of zeros N(T) is asymptotically (T/2π) log(T/2πe) with an error of O(log T).
-/
theorem zero_counting_main_term (h : RiemannVonMangoldtProperty) :
    (fun T => (NZeros T : ℝ) - (T / (2 * Real.pi)) * Real.log (T / (2 * Real.pi * Real.exp 1))) 
    =O[Filter.atTop] (fun T => Real.log T) :=
  zero_counting_main_term_of_RiemannVonMangoldt h