/-
# Jensen's Formula and Zero Counting for Order-1 Entire Functions

If f is an entire function with |f(s)| ≤ exp(C|s|·log|s|) for |s| ≥ 2, and f(0) ≠ 0,
then the number of zeros of f in |s| ≤ R satisfies N(R) ≤ C'·R·log(R+1).

The proof applies Jensen's formula on the disk of radius 2R. The circle average of
log|f| is bounded by C·(2R)·log(2R). Each zero in |s|≤R contributes log(2R/|ρ|) ≥ log 2.
So N(R)·log 2 ≤ C·2R·log(2R).

DELIVERABLE 2: Specialization to RiemannXiAlt using xi_growth_bound.

NOTE: This file was generated by Aristotle (project 4f93cc00) and fixed by Claude Code.
The `exact?` at line 85 was replaced with `exact entire_meromorphicOn hf _`.
-/
import Littlewood.Aristotle.Standalone.JensenZeroCounting
import Littlewood.Aristotle.Standalone.XiGrowthBound

set_option maxHeartbeats 800000

open MeromorphicOn Metric Real Filter Complex Topology
open Aristotle.Standalone.XiGrowthBound

noncomputable section

/-! ## Circle average bound for order-1 growth -/

/-
The circle average of log ‖f‖ is bounded by C * (2R) * log(2R) under order-1 growth.
-/
lemma circleAverage_log_norm_bound_order_one {f : ℂ → ℂ} {C : ℝ}
    (hbound : ∀ s : ℂ, 2 ≤ ‖s‖ → Real.log ‖f s‖ ≤ C * ‖s‖ * Real.log ‖s‖)
    (hf : ∀ z, AnalyticAt ℂ f z) {R : ℝ} (hR : 1 ≤ R) :
    circleAverage (fun s => Real.log ‖f s‖) 0 (2 * R) ≤
      C * (2 * R) * Real.log (2 * R) := by
  simp_all +decide [ circleAverage ];
  rw [ intervalIntegral.integral_of_le ( by positivity ) ];
  -- Apply the bound from hbound to each term in the integral.
  have h_integral_bound : ∀ x ∈ Set.Ioc 0 (2 * Real.pi), Real.log ‖f (circleMap 0 (2 * R) x)‖ ≤ C * (2 * R) * Real.log (2 * R) := by
    intro x hx; convert hbound ( circleMap 0 ( 2 * R ) x ) _ using 1 <;> norm_num [ abs_of_nonneg ( by linarith : 0 ≤ 2 * R ) ] ;
    linarith;
  by_cases h_integrable : MeasureTheory.IntegrableOn (fun x => Real.log ‖f (circleMap 0 (2 * R) x)‖) (Set.Ioc 0 (2 * Real.pi)) MeasureTheory.MeasureSpace.volume;
  · refine' le_trans ( mul_le_mul_of_nonneg_left ( MeasureTheory.setIntegral_mono_on _ _ measurableSet_Ioc h_integral_bound ) ( by positivity ) ) _ <;> norm_num [ Real.pi_pos.le ];
    · exact h_integrable;
    · exact MeasureTheory.integrable_const _;
    · ring_nf; norm_num [ Real.pi_pos.ne' ];
  · rw [ MeasureTheory.integral_undef h_integrable ] ; norm_num;
    contrapose! h_integrable;
    refine' ContinuousOn.integrableOn_Icc _ |> fun h => h.mono_set <| Set.Ioc_subset_Icc_self;
    refine' ContinuousOn.log _ _;
    · exact ContinuousOn.norm ( ContinuousOn.comp ( show ContinuousOn f ( Set.univ : Set ℂ ) from fun z hz => ( hf z |> AnalyticAt.continuousAt |> ContinuousAt.continuousWithinAt ) ) ( Continuous.continuousOn ( by continuity ) ) fun x hx => Set.mem_univ _ );
    · intro x hx; intro H; specialize h_integral_bound x; simp_all +decide [ Real.log_le_iff_le_exp ] ;
      cases lt_or_eq_of_le hx.1 <;> simp_all +decide [ circleMap ];
      · linarith;
      · subst_vars; nlinarith [ Real.pi_pos, show 0 ≤ C * ( 2 * R ) * Real.log ( 2 * R ) by exact mul_nonneg ( mul_nonneg ( show 0 ≤ C by
                                                                                                                              contrapose! hbound;
                                                                                                                              refine' ⟨ 2 * R, _, _ ⟩ <;> norm_num [ abs_of_nonneg, hR ];
                                                                                                                              · rw [ abs_of_nonneg ] <;> linarith;
                                                                                                                              · simp_all +decide [ abs_of_nonneg ( by linarith : 0 ≤ R ) ] ) ( by positivity ) ) ( Real.log_nonneg ( by linarith ) ) ] ;

/-! ## Main theorem: order-1 zero counting bound -/

/-
**Zero-counting bound for entire functions of order 1.**
If f is entire with |f(s)| ≤ exp(C|s|·log|s|) for |s| ≥ 2, and f(0) ≠ 0,
then the number of zeros of f in |s| ≤ R is O(R·log R).
-/
theorem entire_zero_count_bound_order_one {f : ℂ → ℂ} {C : ℝ}
    (hf : ∀ z, AnalyticAt ℂ f z) (hC : 0 < C)
    (hbound : ∀ s, 2 ≤ ‖s‖ → ‖f s‖ ≤ Real.exp (C * ‖s‖ * Real.log ‖s‖))
    (hf0 : f 0 ≠ 0) :
    ∃ C', 0 < C' ∧ ∀ R, 1 ≤ R →
      (zeroCount f R : ℝ) ≤ C' * R * Real.log (R + 1) := by
  -- Apply Jensen's formula via `MeromorphicOn.circleAverage_log_norm` on disk of radius 2R.
  have h_jensen : ∀ R : ℝ, 1 ≤ R → circleAverage (fun s => Real.log ‖f s‖) 0 (2 * R) ≤ C * (2 * R) * Real.log (2 * R) := by
    apply_rules [ circleAverage_log_norm_bound_order_one ];
    intro s hs; specialize hbound s hs; contrapose! hbound;
    rw [ ← Real.exp_log ( norm_pos_iff.mpr <| show f s ≠ 0 from fun h => by norm_num [ h ] at hbound; nlinarith [ show 0 ≤ C * ‖s‖ * Real.log ‖s‖ by exact mul_nonneg ( mul_nonneg hC.le <| norm_nonneg _ ) <| Real.log_nonneg <| by linarith ] ) ] ; gcongr;
  -- By `jensen_sum_lower_bound`, the zero sum is ≥ zeroCount * log 2. Combined with Jensen:
  have h_jensen_sum : ∀ R : ℝ, 1 ≤ R → (zeroCount f R : ℝ) * Real.log 2 ≤ C * (2 * R) * Real.log (2 * R) - Real.log ‖meromorphicTrailingCoeffAt f 0‖ := by
    intro R hR
    have h_jensen_sum : (zeroCount f R : ℝ) * Real.log 2 ≤ circleAverage (fun s => Real.log ‖f s‖) 0 (2 * R) - Real.log ‖meromorphicTrailingCoeffAt f 0‖ := by
      convert jensen_sum_lower_bound hf hf0 hR using 1;
      rw [ MeromorphicOn.circleAverage_log_norm ];
      · rw [ abs_of_nonneg ( by positivity ) ] ; rw [ divisor_zero_of_ne_zero hf hf0 ] ; norm_num;
        norm_num [ show 0 ≤ 2 * R by positivity ];
      · positivity;
      · exact entire_meromorphicOn hf _  -- FIXED: was `exact?`
    exact le_trans h_jensen_sum ( sub_le_sub_right ( h_jensen R hR ) _ );
  -- Note log(2*R) = log 2 + log R ≤ 2*log(R+1) (for R ≥ 1), so zeroCount * log 2 ≤ 4*C*R*log(R+1) + L.
  have h_log_bound : ∀ R : ℝ, 1 ≤ R → (zeroCount f R : ℝ) * Real.log 2 ≤ 4 * C * R * Real.log (R + 1) + |Real.log ‖meromorphicTrailingCoeffAt f 0‖| := by
    intros R hR
    specialize h_jensen_sum R hR
    have h_log_bound_step : Real.log (2 * R) ≤ 2 * Real.log (R + 1) := by
      rw [ ← Real.log_rpow, Real.log_le_log_iff ] <;> norm_num <;> nlinarith;
    cases abs_cases ( Real.log ‖meromorphicTrailingCoeffAt f 0‖ ) <;> nlinarith [ show 0 ≤ C * R by positivity ];
  -- Choose C' = 4*C/log 2 + L/(log 2)^2 + 1.
  use 4 * C / Real.log 2 + |Real.log ‖meromorphicTrailingCoeffAt f 0‖| / (Real.log 2)^2 + 1;
  refine' ⟨ _, fun R hR => _ ⟩;
  · positivity;
  · field_simp;
    -- Since $R \geq 1$, we have $R \cdot \log(R+1) \geq \log 2$.
    have h_log_bound : R * Real.log (R + 1) ≥ Real.log 2 := by
      exact le_trans ( Real.log_le_log ( by norm_num ) ( by linarith ) ) ( le_mul_of_one_le_left ( Real.log_nonneg ( by linarith ) ) hR );
    nlinarith [ Real.log_pos one_lt_two, abs_nonneg ( Real.log ‖meromorphicTrailingCoeffAt f 0‖ ), ‹∀ R : ℝ, 1 ≤ R → ( zeroCount f R : ℝ ) * Real.log 2 ≤ 4 * C * R * Real.log ( R + 1 ) + |Real.log ‖meromorphicTrailingCoeffAt f 0‖|› R hR, mul_le_mul_of_nonneg_left h_log_bound <| Real.log_nonneg one_le_two ]

/-! ## DELIVERABLE 2: Specialization to RiemannXiAlt -/

theorem RiemannXiAlt_analyticAt : ∀ z, AnalyticAt ℂ RiemannXiAlt z :=
  differentiable_RiemannXiAlt.analyticAt

theorem RiemannXiAlt_zero_ne : RiemannXiAlt 0 ≠ 0 := by
  unfold RiemannXiAlt; norm_num;

/-- **Key theorem**: N(R) ≤ C'·R·log(R+1) for zeros of RiemannXiAlt.
    This is the classical N(T) = O(T log T) zero count. -/
theorem xi_zero_count_R_logR :
    ∃ C' : ℝ, 0 < C' ∧ ∀ R : ℝ, 1 ≤ R →
      (zeroCount RiemannXiAlt R : ℝ) ≤ C' * R * Real.log (R + 1) := by
  obtain ⟨C, hC, hbound⟩ := xi_growth_bound
  exact entire_zero_count_bound_order_one RiemannXiAlt_analyticAt hC hbound RiemannXiAlt_zero_ne

end
