/-
Kronecker's equidistribution / density theorem infrastructure.

## Main results

### Density of additive subgroups of ℝ
* `irrational_iff_dense_subgroup`: {mα + n} dense in ℝ iff α irrational.
* `irrational_dense_subgroup`: if α irrational, {mα + n} dense in ℝ.
* `dense_closure_of_irrational_element`: if a finite set of reals contains 1 and an
  irrational, the ℤ-span is dense in ℝ. Proved via `AddSubgroup.dense_or_cyclic`.

### 1D Inhomogeneous Kronecker theorem
* `inhomogeneous_1d_approx`: if α irrational, for any θ, ε > 0, ∃ m n ∈ ℤ
  with |mα + n − θ| < ε.
* `inhomogeneous_1d_approx_mod`: version modulo 2π.

### Complex phase alignment
* `complex_exp_I_sub_norm_le`: |e^{iθ₁} − e^{iθ₂}| ≤ |θ₁ − θ₂|.
* `kronecker_1d_phase_density`: {e^{ikα} : k ∈ ℤ} dense in S¹ for α/(2π) irrational.
* `single_frequency_phase_alignment`: exact phase alignment for one frequency.
* `exists_large_x_single_phase_to_target`: ∃ x > X with e^{iγ log x} ≈ e^{iθ}.

## Context

These results provide the 1D foundation for closing `PhaseAlignmentToTargetHyp`, which
requires the multi-dimensional equal-target case. The multi-dimensional Kronecker theorem
(n ≥ 2) requires either Pontryagin duality or the structure theorem for closed subgroups
of ℝⁿ, neither of which is currently in Mathlib. The 1D case here is sufficient for
single-frequency phase alignment and provides infrastructure for the general case.

## References

* Kronecker 1884, Hardy-Wright (2008) §23.8, Weyl 1916.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators Real
open Set Filter Topology Metric Real Complex

set_option maxHeartbeats 1600000
set_option maxRecDepth 2000

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

namespace Kronecker

/-! ### Part 1: Density of additive subgroups of ℝ -/

/-- The additive subgroup generated by α and 1 is dense iff α is irrational.
    Specialization of `dense_addSubgroupClosure_pair_iff` to b = 1. -/
theorem irrational_iff_dense_subgroup {α : ℝ} :
    Irrational α ↔ Dense (AddSubgroup.closure {α, 1} : Set ℝ) := by
  rw [dense_addSubgroupClosure_pair_iff, div_one]

/-- If α is irrational, then {mα + n : m, n ∈ ℤ} is dense in ℝ. -/
theorem irrational_dense_subgroup {α : ℝ} (hα : Irrational α) :
    Dense (AddSubgroup.closure {α, 1} : Set ℝ) :=
  irrational_iff_dense_subgroup.mp hα

/-- If a finite set S ⊆ ℝ contains 1 and at least one irrational element, then
    the additive subgroup closure of S is dense in ℝ.

    Proof: by `AddSubgroup.dense_or_cyclic`, the closure is either dense or
    cyclic (= ℤ·c for some c). If cyclic, then 1 = mc gives c = 1/m, so every
    element of S equals n/m ∈ ℚ, contradicting the irrational element. -/
theorem dense_closure_of_irrational_element
    {S : Finset ℝ} (h1 : (1 : ℝ) ∈ S) (hα : ∃ α ∈ S, Irrational α) :
    Dense (AddSubgroup.closure (S : Set ℝ) : Set ℝ) := by
  rcases AddSubgroup.dense_or_cyclic (AddSubgroup.closure (S : Set ℝ)) with hd | ⟨c, hc⟩
  · exact hd
  · exfalso
    obtain ⟨α, hαS, hαirr⟩ := hα
    have h1_mem := AddSubgroup.subset_closure (show (1 : ℝ) ∈ (S : Set ℝ) from h1)
    have hα_mem := AddSubgroup.subset_closure (show α ∈ (S : Set ℝ) from hαS)
    rw [hc, SetLike.mem_coe, AddSubgroup.mem_closure_singleton] at h1_mem hα_mem
    obtain ⟨m, hm⟩ := h1_mem
    obtain ⟨n, hn⟩ := hα_mem
    have hm_ne : (m : ℤ) ≠ 0 := by rintro rfl; simp at hm
    exact hαirr ⟨n / m, by
      have hc_ne : c ≠ 0 := by intro h; simp [h] at hm
      rw [show α = (n : ℝ) * c from by rw [← zsmul_eq_mul]; exact hn.symm,
          show c = 1 / (m : ℝ) from by
            have : (m : ℝ) * c = 1 := by rw [← zsmul_eq_mul]; exact hm
            field_simp at this ⊢; linarith]
      push_cast; ring⟩

/-! ### Part 2: 1D Inhomogeneous Kronecker theorem -/

/-- **1D Inhomogeneous Kronecker theorem**: If α is irrational, then for any target θ ∈ ℝ
    and precision ε > 0, there exist m, n ∈ ℤ with |mα + n − θ| < ε.

    This says {mα mod 1 : m ∈ ℤ} is dense in [0,1). -/
theorem inhomogeneous_1d_approx {α : ℝ} (hα : Irrational α) (θ : ℝ) {ε : ℝ} (hε : ε > 0) :
    ∃ m n : ℤ, |m * α + n - θ| < ε := by
  have hd := irrational_dense_subgroup hα
  rw [Metric.dense_iff] at hd
  obtain ⟨y, hy_mem, hy_close⟩ := hd θ ε hε
  rw [show ({α, 1} : Set ℝ) = {α} ∪ {1} from by ext; simp [or_comm],
      AddSubgroup.closure_union,
      ← AddSubgroup.zmultiples_eq_closure, ← AddSubgroup.zmultiples_eq_closure,
      SetLike.mem_coe, AddSubgroup.mem_sup] at hy_close
  obtain ⟨a, ha, b, hb, rfl⟩ := hy_close
  rw [AddSubgroup.mem_zmultiples_iff] at ha hb
  obtain ⟨m, rfl⟩ := ha; obtain ⟨n, rfl⟩ := hb
  exact ⟨m, n, by
    simp only [zsmul_eq_mul, mul_one] at hy_mem ⊢
    rwa [Metric.mem_ball, Real.dist_eq] at hy_mem⟩

/-- **1D inhomogeneous approximation modulo 2π**: If α/(2π) is irrational, then
    for any target θ ∈ ℝ and ε > 0, there exists m ∈ ℤ with |mα − θ| < ε (mod 2π). -/
theorem inhomogeneous_1d_approx_mod {α : ℝ} (hα : Irrational (α / (2 * Real.pi)))
    (θ : ℝ) {ε : ℝ} (hε : ε > 0) :
    ∃ m : ℤ, ∃ k : ℤ, |m * α - θ - k * (2 * Real.pi)| < ε := by
  have hpi_pos : (0 : ℝ) < 2 * Real.pi := by positivity
  obtain ⟨m, k, h⟩ := inhomogeneous_1d_approx hα (θ / (2 * Real.pi))
    (ε := ε / (2 * Real.pi)) (by positivity)
  refine ⟨m, -k, ?_⟩
  have key : ↑m * α - θ - ↑(-k) * (2 * Real.pi) =
    (↑m * (α / (2 * Real.pi)) + ↑k - θ / (2 * Real.pi)) * (2 * Real.pi) := by
    push_cast; field_simp; ring
  rw [key, abs_mul, abs_of_pos hpi_pos]
  calc |↑m * (α / (2 * Real.pi)) + ↑k - θ / (2 * Real.pi)| * (2 * Real.pi)
      < ε / (2 * Real.pi) * (2 * Real.pi) :=
        mul_lt_mul_of_pos_right h hpi_pos
    _ = ε := by field_simp

/-! ### Part 3: Complex phase alignment lemmas -/

/-- |e^{iθ₁} − e^{iθ₂}| ≤ |θ₁ − θ₂| for real θ₁, θ₂.
    Uses `Real.norm_exp_I_mul_ofReal_sub_one_le` from Mathlib. -/
theorem complex_exp_I_sub_norm_le (θ₁ θ₂ : ℝ) :
    ‖Complex.exp (Complex.I * θ₁) - Complex.exp (Complex.I * θ₂)‖ ≤ |θ₁ - θ₂| := by
  rw [show Complex.I * (θ₁ : ℂ) = Complex.I * θ₂ + Complex.I * (↑(θ₁ - θ₂)) by
        push_cast; ring,
      Complex.exp_add,
      show Complex.exp (Complex.I * ↑θ₂) * Complex.exp (Complex.I * ↑(θ₁ - θ₂)) -
        Complex.exp (Complex.I * ↑θ₂) =
        Complex.exp (Complex.I * ↑θ₂) * (Complex.exp (Complex.I * ↑(θ₁ - θ₂)) - 1) from by ring,
      norm_mul]
  have h1 : ‖Complex.exp (Complex.I * ↑θ₂)‖ = 1 := by
    rw [show Complex.I * (↑θ₂ : ℂ) = ↑θ₂ * Complex.I by ring]
    exact Complex.norm_exp_ofReal_mul_I θ₂
  rw [h1, one_mul]
  exact le_trans Real.norm_exp_I_mul_ofReal_sub_one_le (le_of_eq (Real.norm_eq_abs _))

/-- For irrational α/(2π), the orbit {e^{ikα} : k ∈ ℤ} is dense in S¹.
    For any target e^{iθ} and precision ε > 0, there exists k ∈ ℤ with
    ‖e^{ikα} − e^{iθ}‖ < ε. -/
theorem kronecker_1d_phase_density
    {α : ℝ} (hα : Irrational (α / (2 * Real.pi)))
    (θ : ℝ) {ε : ℝ} (hε : ε > 0) :
    ∃ k : ℤ, ‖Complex.exp (Complex.I * (k * α)) -
              Complex.exp (Complex.I * θ)‖ < ε := by
  obtain ⟨m, j, hm⟩ := inhomogeneous_1d_approx_mod hα θ hε
  refine ⟨m, ?_⟩
  set val := (m : ℝ) * α - (j : ℝ) * (2 * Real.pi)
  have hexp_eq : Complex.exp (Complex.I * ((m : ℤ) * (α : ℂ))) =
      Complex.exp (Complex.I * (val : ℂ)) := by
    have hsplit : Complex.I * ((m : ℤ) * (α : ℂ)) =
        Complex.I * (val : ℂ) + ↑j * (2 * ↑Real.pi * Complex.I) := by
      simp only [val]; push_cast; ring
    rw [hsplit, Complex.exp_add, Complex.exp_int_mul_two_pi_mul_I, mul_one]
  rw [hexp_eq]
  calc ‖Complex.exp (Complex.I * (val : ℂ)) - Complex.exp (Complex.I * (θ : ℂ))‖
      ≤ |val - θ| := complex_exp_I_sub_norm_le val θ
    _ = |(m : ℝ) * α - θ - (j : ℝ) * (2 * Real.pi)| := by simp only [val]; congr 1; ring
    _ < ε := hm

/-! ### Part 4: Single-frequency exact phase alignment -/

/-- For any single positive frequency γ, we can place a phase EXACTLY on target
    by choosing the right t. No irrationality needed — just periodicity.
    Returns t > L with γt = θ + 2πk for some integer k. -/
theorem single_frequency_phase_alignment
    {γ : ℝ} (hγ : γ > 0) (θ : ℝ) (L : ℝ) :
    ∃ t : ℝ, t > L ∧ ∃ k : ℤ, γ * t = θ + 2 * Real.pi * k := by
  have hpi := Real.pi_pos
  set k₀ : ℤ := ⌊(L * γ - θ) / (2 * Real.pi)⌋ + 1
  have hk₀ : (L * γ - θ) / (2 * Real.pi) < k₀ := by
    push_cast [k₀]; exact Int.lt_floor_add_one _
  refine ⟨(θ + 2 * Real.pi * k₀) / γ, ?_, k₀, by field_simp⟩
  show L < (θ + 2 * Real.pi * ↑k₀) / γ
  rw [lt_div_iff₀ hγ]
  have := (div_lt_iff₀ (by positivity : (2 : ℝ) * Real.pi > 0)).mp hk₀
  linarith

/-- For any γ > 0, target θ, precision ε > 0, and threshold X, there exists x > X
    with ‖e^{iγ log x} − e^{iθ}‖ < ε. Single-frequency phase alignment
    to arbitrary target on S¹. No irrationality assumption needed. -/
theorem exists_large_x_single_phase_to_target
    {γ : ℝ} (hγ : γ > 0) (θ : ℝ) (ε : ℝ) (hε : ε > 0) (X : ℝ) :
    ∃ x : ℝ, x > X ∧ 1 < x ∧
      ‖Complex.exp (Complex.I * (γ * Real.log x)) -
       Complex.exp (Complex.I * θ)‖ < ε := by
  have hpi := Real.pi_pos
  set L : ℝ := Real.log (max X 1) + 1
  obtain ⟨k : ℤ, hk⟩ : ∃ k : ℤ, (L * γ - θ) / (2 * Real.pi) < k :=
    ⟨⌊(L * γ - θ) / (2 * Real.pi)⌋ + 1, by push_cast; exact Int.lt_floor_add_one _⟩
  set t : ℝ := (θ + 2 * Real.pi * k) / γ
  have ht_gt_L : t > L := by
    rw [show t = (θ + 2 * Real.pi * k) / γ from rfl, gt_iff_lt, lt_div_iff₀ hγ]
    nlinarith [(div_lt_iff₀ (by positivity : (2 : ℝ) * Real.pi > 0)).mp hk]
  have hL_pos : L ≥ 1 := by
    simp only [L]; linarith [Real.log_nonneg (le_max_right X 1)]
  have ht_pos : t > 0 := by linarith
  have ht_exact : γ * t = θ + 2 * Real.pi * k := by
    rw [show t = (θ + 2 * Real.pi * k) / γ from rfl]; field_simp
  use Real.exp t
  refine ⟨?_, ?_, ?_⟩
  · calc X ≤ max X 1 := le_max_left _ _
      _ = Real.exp (Real.log (max X 1)) := (Real.exp_log (by positivity)).symm
      _ < Real.exp t := Real.exp_strictMono (by linarith)
  · calc (1 : ℝ) = Real.exp 0 := Real.exp_zero.symm
      _ < Real.exp t := Real.exp_strictMono ht_pos
  · -- Phase: γt = θ + 2πk so exp(iγt) = exp(iθ)·exp(2πik) = exp(iθ)
    rw [Real.log_exp]
    conv_lhs =>
      rw [show Complex.I * (↑γ * ↑t) = Complex.I * ↑(γ * t) by push_cast; ring]
    rw [ht_exact,
        show Complex.I * ↑(θ + 2 * Real.pi * ↑k) =
          Complex.I * ↑θ + ↑k * (2 * ↑Real.pi * Complex.I) by push_cast; ring,
        Complex.exp_add, Complex.exp_int_mul_two_pi_mul_I, mul_one]
    simp [hε]

/-! ### Part 5: Infrastructure for multi-dimensional case

The full `PhaseAlignmentToTargetHyp` requires aligning MULTIPLE frequencies γ₁,...,γₙ
simultaneously to the same target w on S¹. This is the equal-target case of the
n-dimensional Kronecker theorem.

The existing `Aristotle.DirichletPhaseAlignment.exists_large_x_phases_aligned_finset`
proves the homogeneous case (w = 1). The gap to arbitrary w requires:

1. The n-dimensional Kronecker theorem on the torus (ℝ/ℤ)ⁿ, which in Lean would need
   either Pontryagin duality (characters separate points) or the structure theorem
   for closed subgroups of ℝⁿ (V ⊕ Λ decomposition).

2. The Q-linear independence of zeta zero ordinates, which follows from RH combined
   with the superlinear growth N(T) ~ (T/2π) log T from Riemann-von Mangoldt.

For the 1D case (single frequency), the results in this file give a complete solution
with no sorry. For n ≥ 2 frequencies, the multi-dimensional generalization remains
an open formalization challenge.
-/

end Kronecker

end
