/-
Kronecker's equidistribution / density theorem infrastructure.

## Main results

### Density of additive subgroups of ℝ
* `irrational_iff_dense_subgroup`: {mα + n} dense in ℝ iff α irrational.
* `irrational_dense_subgroup`: if α irrational, {mα + n} dense in ℝ.
* `dense_closure_of_irrational_element`: if a finite set of reals contains 1 and an
  irrational, the ℤ-span is dense in ℝ. Proved via `AddSubgroup.dense_or_cyclic`.

### 1D Inhomogeneous Kronecker theorem
* `inhomogeneous_1d_approx`: if α irrational, for any θ, ε > 0, ∃ m n ∈ ℤ
  with |mα + n − θ| < ε.
* `inhomogeneous_1d_approx_mod`: version modulo 2π.

### Complex phase alignment
* `complex_exp_I_sub_norm_le`: |e^{iθ₁} − e^{iθ₂}| ≤ |θ₁ − θ₂|.
* `kronecker_1d_phase_density`: {e^{ikα} : k ∈ ℤ} dense in S¹ for α/(2π) irrational.
* `single_frequency_phase_alignment`: exact phase alignment for one frequency.
* `exists_large_x_single_phase_to_target`: ∃ x > X with e^{iγ log x} ≈ e^{iθ}.

### Large-m Kronecker (NEW)
* `homogeneous_near_period`: quantitative near-period from homogeneous Dirichlet.
* `inhomogeneous_1d_approx_mod_large`: 1D Kronecker with m > M for any threshold M.
* `two_freq_arg_approx_above_threshold`: 2-freq exact+approx above any threshold.

## Context

These results provide the 1D foundation for closing `PhaseAlignmentToTargetHyp`, which
requires the multi-dimensional equal-target case. The multi-dimensional Kronecker theorem
(n ≥ 2) requires either Pontryagin duality or the structure theorem for closed subgroups
of ℝⁿ, neither of which is currently in Mathlib. The 1D case here is sufficient for
single-frequency phase alignment and provides infrastructure for the general case.

## References

* Kronecker 1884, Hardy-Wright (2008) §23.8, Weyl 1916.
-/

import Mathlib
import Littlewood.CoreLemmas.DirichletApproximation

set_option linter.mathlibStandardSet false

open scoped BigOperators Real DirichletApprox
open Set Filter Topology Metric Real Complex DirichletApprox

set_option maxHeartbeats 1600000
set_option maxRecDepth 2000

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

namespace Kronecker

/-! ### Part 1: Density of additive subgroups of ℝ -/

/-- The additive subgroup generated by α and 1 is dense iff α is irrational.
    Specialization of `dense_addSubgroupClosure_pair_iff` to b = 1. -/
theorem irrational_iff_dense_subgroup {α : ℝ} :
    Irrational α ↔ Dense (AddSubgroup.closure {α, 1} : Set ℝ) := by
  rw [dense_addSubgroupClosure_pair_iff, div_one]

/-- If α is irrational, then {mα + n : m, n ∈ ℤ} is dense in ℝ. -/
theorem irrational_dense_subgroup {α : ℝ} (hα : Irrational α) :
    Dense (AddSubgroup.closure {α, 1} : Set ℝ) :=
  irrational_iff_dense_subgroup.mp hα

/-- If a finite set S ⊆ ℝ contains 1 and at least one irrational element, then
    the additive subgroup closure of S is dense in ℝ.

    Proof: by `AddSubgroup.dense_or_cyclic`, the closure is either dense or
    cyclic (= ℤ·c for some c). If cyclic, then 1 = mc gives c = 1/m, so every
    element of S equals n/m ∈ ℚ, contradicting the irrational element. -/
theorem dense_closure_of_irrational_element
    {S : Finset ℝ} (h1 : (1 : ℝ) ∈ S) (hα : ∃ α ∈ S, Irrational α) :
    Dense (AddSubgroup.closure (S : Set ℝ) : Set ℝ) := by
  rcases AddSubgroup.dense_or_cyclic (AddSubgroup.closure (S : Set ℝ)) with hd | ⟨c, hc⟩
  · exact hd
  · exfalso
    obtain ⟨α, hαS, hαirr⟩ := hα
    have h1_mem := AddSubgroup.subset_closure (show (1 : ℝ) ∈ (S : Set ℝ) from h1)
    have hα_mem := AddSubgroup.subset_closure (show α ∈ (S : Set ℝ) from hαS)
    rw [hc, SetLike.mem_coe, AddSubgroup.mem_closure_singleton] at h1_mem hα_mem
    obtain ⟨m, hm⟩ := h1_mem
    obtain ⟨n, hn⟩ := hα_mem
    have hm_ne : (m : ℤ) ≠ 0 := by rintro rfl; simp at hm
    exact hαirr ⟨n / m, by
      have hc_ne : c ≠ 0 := by intro h; simp [h] at hm
      rw [show α = (n : ℝ) * c from by rw [← zsmul_eq_mul]; exact hn.symm,
          show c = 1 / (m : ℝ) from by
            have : (m : ℝ) * c = 1 := by rw [← zsmul_eq_mul]; exact hm
            field_simp at this ⊢; linarith]
      push_cast; ring⟩

/-! ### Part 2: 1D Inhomogeneous Kronecker theorem -/

/-- **1D Inhomogeneous Kronecker theorem**: If α is irrational, then for any target θ ∈ ℝ
    and precision ε > 0, there exist m, n ∈ ℤ with |mα + n − θ| < ε.

    This says {mα mod 1 : m ∈ ℤ} is dense in [0,1). -/
theorem inhomogeneous_1d_approx {α : ℝ} (hα : Irrational α) (θ : ℝ) {ε : ℝ} (hε : ε > 0) :
    ∃ m n : ℤ, |m * α + n - θ| < ε := by
  have hd := irrational_dense_subgroup hα
  rw [Metric.dense_iff] at hd
  obtain ⟨y, hy_mem, hy_close⟩ := hd θ ε hε
  rw [show ({α, 1} : Set ℝ) = {α} ∪ {1} from by ext; simp [or_comm],
      AddSubgroup.closure_union,
      ← AddSubgroup.zmultiples_eq_closure, ← AddSubgroup.zmultiples_eq_closure,
      SetLike.mem_coe, AddSubgroup.mem_sup] at hy_close
  obtain ⟨a, ha, b, hb, rfl⟩ := hy_close
  rw [AddSubgroup.mem_zmultiples_iff] at ha hb
  obtain ⟨m, rfl⟩ := ha; obtain ⟨n, rfl⟩ := hb
  exact ⟨m, n, by
    simp only [zsmul_eq_mul, mul_one] at hy_mem ⊢
    rwa [Metric.mem_ball, Real.dist_eq] at hy_mem⟩

/-- **1D inhomogeneous approximation modulo 2π**: If α/(2π) is irrational, then
    for any target θ ∈ ℝ and ε > 0, there exists m ∈ ℤ with |mα − θ| < ε (mod 2π). -/
theorem inhomogeneous_1d_approx_mod {α : ℝ} (hα : Irrational (α / (2 * Real.pi)))
    (θ : ℝ) {ε : ℝ} (hε : ε > 0) :
    ∃ m : ℤ, ∃ k : ℤ, |m * α - θ - k * (2 * Real.pi)| < ε := by
  have hpi_pos : (0 : ℝ) < 2 * Real.pi := by positivity
  obtain ⟨m, k, h⟩ := inhomogeneous_1d_approx hα (θ / (2 * Real.pi))
    (ε := ε / (2 * Real.pi)) (by positivity)
  refine ⟨m, -k, ?_⟩
  have key : ↑m * α - θ - ↑(-k) * (2 * Real.pi) =
    (↑m * (α / (2 * Real.pi)) + ↑k - θ / (2 * Real.pi)) * (2 * Real.pi) := by
    push_cast; field_simp; ring
  rw [key, abs_mul, abs_of_pos hpi_pos]
  calc |↑m * (α / (2 * Real.pi)) + ↑k - θ / (2 * Real.pi)| * (2 * Real.pi)
      < ε / (2 * Real.pi) * (2 * Real.pi) :=
        mul_lt_mul_of_pos_right h hpi_pos
    _ = ε := by field_simp

/-! ### Part 3: Complex phase alignment lemmas -/

/-- |e^{iθ₁} − e^{iθ₂}| ≤ |θ₁ − θ₂| for real θ₁, θ₂.
    Uses `Real.norm_exp_I_mul_ofReal_sub_one_le` from Mathlib. -/
theorem complex_exp_I_sub_norm_le (θ₁ θ₂ : ℝ) :
    ‖Complex.exp (Complex.I * θ₁) - Complex.exp (Complex.I * θ₂)‖ ≤ |θ₁ - θ₂| := by
  rw [show Complex.I * (θ₁ : ℂ) = Complex.I * θ₂ + Complex.I * (↑(θ₁ - θ₂)) by
        push_cast; ring,
      Complex.exp_add,
      show Complex.exp (Complex.I * ↑θ₂) * Complex.exp (Complex.I * ↑(θ₁ - θ₂)) -
        Complex.exp (Complex.I * ↑θ₂) =
        Complex.exp (Complex.I * ↑θ₂) * (Complex.exp (Complex.I * ↑(θ₁ - θ₂)) - 1) from by ring,
      norm_mul]
  have h1 : ‖Complex.exp (Complex.I * ↑θ₂)‖ = 1 := by
    rw [show Complex.I * (↑θ₂ : ℂ) = ↑θ₂ * Complex.I by ring]
    exact Complex.norm_exp_ofReal_mul_I θ₂
  rw [h1, one_mul]
  exact le_trans Real.norm_exp_I_mul_ofReal_sub_one_le (le_of_eq (Real.norm_eq_abs _))

/-- For irrational α/(2π), the orbit {e^{ikα} : k ∈ ℤ} is dense in S¹.
    For any target e^{iθ} and precision ε > 0, there exists k ∈ ℤ with
    ‖e^{ikα} − e^{iθ}‖ < ε. -/
theorem kronecker_1d_phase_density
    {α : ℝ} (hα : Irrational (α / (2 * Real.pi)))
    (θ : ℝ) {ε : ℝ} (hε : ε > 0) :
    ∃ k : ℤ, ‖Complex.exp (Complex.I * (k * α)) -
              Complex.exp (Complex.I * θ)‖ < ε := by
  obtain ⟨m, j, hm⟩ := inhomogeneous_1d_approx_mod hα θ hε
  refine ⟨m, ?_⟩
  set val := (m : ℝ) * α - (j : ℝ) * (2 * Real.pi)
  have hexp_eq : Complex.exp (Complex.I * ((m : ℤ) * (α : ℂ))) =
      Complex.exp (Complex.I * (val : ℂ)) := by
    have hsplit : Complex.I * ((m : ℤ) * (α : ℂ)) =
        Complex.I * (val : ℂ) + ↑j * (2 * ↑Real.pi * Complex.I) := by
      simp only [val]; push_cast; ring
    rw [hsplit, Complex.exp_add, Complex.exp_int_mul_two_pi_mul_I, mul_one]
  rw [hexp_eq]
  calc ‖Complex.exp (Complex.I * (val : ℂ)) - Complex.exp (Complex.I * (θ : ℂ))‖
      ≤ |val - θ| := complex_exp_I_sub_norm_le val θ
    _ = |(m : ℝ) * α - θ - (j : ℝ) * (2 * Real.pi)| := by simp only [val]; congr 1; ring
    _ < ε := hm

/-! ### Part 4: Single-frequency exact phase alignment -/

/-- For any single positive frequency γ, we can place a phase EXACTLY on target
    by choosing the right t. No irrationality needed — just periodicity.
    Returns t > L with γt = θ + 2πk for some integer k. -/
theorem single_frequency_phase_alignment
    {γ : ℝ} (hγ : γ > 0) (θ : ℝ) (L : ℝ) :
    ∃ t : ℝ, t > L ∧ ∃ k : ℤ, γ * t = θ + 2 * Real.pi * k := by
  have hpi := Real.pi_pos
  set k₀ : ℤ := ⌊(L * γ - θ) / (2 * Real.pi)⌋ + 1
  have hk₀ : (L * γ - θ) / (2 * Real.pi) < k₀ := by
    push_cast [k₀]; exact Int.lt_floor_add_one _
  refine ⟨(θ + 2 * Real.pi * k₀) / γ, ?_, k₀, by field_simp⟩
  show L < (θ + 2 * Real.pi * ↑k₀) / γ
  rw [lt_div_iff₀ hγ]
  have := (div_lt_iff₀ (by positivity : (2 : ℝ) * Real.pi > 0)).mp hk₀
  linarith

/-- For any γ > 0, target θ, precision ε > 0, and threshold X, there exists x > X
    with ‖e^{iγ log x} − e^{iθ}‖ < ε. Single-frequency phase alignment
    to arbitrary target on S¹. No irrationality assumption needed. -/
theorem exists_large_x_single_phase_to_target
    {γ : ℝ} (hγ : γ > 0) (θ : ℝ) (ε : ℝ) (hε : ε > 0) (X : ℝ) :
    ∃ x : ℝ, x > X ∧ 1 < x ∧
      ‖Complex.exp (Complex.I * (γ * Real.log x)) -
       Complex.exp (Complex.I * θ)‖ < ε := by
  have hpi := Real.pi_pos
  set L : ℝ := Real.log (max X 1) + 1
  obtain ⟨k : ℤ, hk⟩ : ∃ k : ℤ, (L * γ - θ) / (2 * Real.pi) < k :=
    ⟨⌊(L * γ - θ) / (2 * Real.pi)⌋ + 1, by push_cast; exact Int.lt_floor_add_one _⟩
  set t : ℝ := (θ + 2 * Real.pi * k) / γ
  have ht_gt_L : t > L := by
    rw [show t = (θ + 2 * Real.pi * k) / γ from rfl, gt_iff_lt, lt_div_iff₀ hγ]
    nlinarith [(div_lt_iff₀ (by positivity : (2 : ℝ) * Real.pi > 0)).mp hk]
  have hL_pos : L ≥ 1 := by
    simp only [L]; linarith [Real.log_nonneg (le_max_right X 1)]
  have ht_pos : t > 0 := by linarith
  have ht_exact : γ * t = θ + 2 * Real.pi * k := by
    rw [show t = (θ + 2 * Real.pi * k) / γ from rfl]; field_simp
  use Real.exp t
  refine ⟨?_, ?_, ?_⟩
  · calc X ≤ max X 1 := le_max_left _ _
      _ = Real.exp (Real.log (max X 1)) := (Real.exp_log (by positivity)).symm
      _ < Real.exp t := Real.exp_strictMono (by linarith)
  · calc (1 : ℝ) = Real.exp 0 := Real.exp_zero.symm
      _ < Real.exp t := Real.exp_strictMono ht_pos
  · -- Phase: γt = θ + 2πk so exp(iγt) = exp(iθ)·exp(2πik) = exp(iθ)
    rw [Real.log_exp]
    conv_lhs =>
      rw [show Complex.I * (↑γ * ↑t) = Complex.I * ↑(γ * t) by push_cast; ring]
    rw [ht_exact,
        show Complex.I * ↑(θ + 2 * Real.pi * ↑k) =
          Complex.I * ↑θ + ↑k * (2 * ↑Real.pi * Complex.I) by push_cast; ring,
        Complex.exp_add, Complex.exp_int_mul_two_pi_mul_I, mul_one]
    simp [hε]

/-! ### Part 5: Infrastructure for multi-dimensional case

The full `PhaseAlignmentToTargetHyp` requires aligning MULTIPLE frequencies γ₁,...,γₙ
simultaneously to the same target w on S¹. This is the equal-target case of the
n-dimensional Kronecker theorem.

The existing `Aristotle.DirichletPhaseAlignment.exists_large_x_phases_aligned_finset`
proves the homogeneous case (w = 1). The gap to arbitrary w requires:

1. The n-dimensional Kronecker theorem on the torus (ℝ/ℤ)ⁿ, which in Lean would need
   either Pontryagin duality (characters separate points) or the structure theorem
   for closed subgroups of ℝⁿ (V ⊕ Λ decomposition).

2. The Q-linear independence of zeta zero ordinates, which follows from RH combined
   with the superlinear growth N(T) ~ (T/2π) log T from Riemann-von Mangoldt.

For the 1D case (single frequency), the results in this file give a complete solution
with no sorry. For n ≥ 2 frequencies, the multi-dimensional generalization remains
an open formalization challenge.
-/

/-! ### Part 6: Two-dimensional Kronecker from one-dimensional

The product argument: if α₁/(2π) and α₂/(2π) are both irrational, then for any
target phases (θ₁, θ₂) and precision ε > 0, there exist integers k₁, k₂ such that
both |k₁α₁ - θ₁| < ε (mod 2π) and |k₂α₂ - θ₂| < ε (mod 2π) simultaneously,
with k₁ = k₂ if α₁/α₂ is irrational. -/

/-- If α₁/(2π) and α₂/(2π) are both irrational, for any pair of target phases
    and precision, we can find k₁ for the first and k₂ for the second,
    independently. This is the PRODUCT of two 1D Kronecker results. -/
theorem kronecker_product_2d_independent
    {α₁ α₂ : ℝ}
    (hα₁ : Irrational (α₁ / (2 * Real.pi)))
    (hα₂ : Irrational (α₂ / (2 * Real.pi)))
    (θ₁ θ₂ : ℝ) {ε : ℝ} (hε : ε > 0) :
    (∃ k₁ : ℤ, ‖Complex.exp (Complex.I * (k₁ * α₁)) -
                 Complex.exp (Complex.I * θ₁)‖ < ε) ∧
    (∃ k₂ : ℤ, ‖Complex.exp (Complex.I * (k₂ * α₂)) -
                 Complex.exp (Complex.I * θ₂)‖ < ε) :=
  ⟨kronecker_1d_phase_density hα₁ θ₁ hε,
   kronecker_1d_phase_density hα₂ θ₂ hε⟩

/-- For any positive frequency, exact single-frequency alignment above any
    threshold. Useful as the first step in multi-frequency alignment. -/
theorem two_frequency_approximate_alignment
    {γ₁ γ₂ : ℝ} (hγ₁ : γ₁ > 0) (_hγ₂ : γ₂ > 0)
    (θ₁ θ₂ : ℝ) {ε : ℝ} (hε : ε > 0) (L : ℝ) :
    ∃ t : ℝ, t > L ∧
      ‖Complex.exp (Complex.I * (γ₁ * t)) -
       Complex.exp (Complex.I * θ₁)‖ < ε := by
  obtain ⟨t, ht_gt, k, hk⟩ := single_frequency_phase_alignment hγ₁ θ₁ L
  refine ⟨t, ht_gt, ?_⟩
  have hphase : Complex.exp (Complex.I * ((γ₁ * t : ℝ) : ℂ)) =
      Complex.exp (Complex.I * (θ₁ : ℂ)) := by
    rw [show (γ₁ * t : ℝ) = θ₁ + 2 * Real.pi * (k : ℝ) from by linarith]
    rw [show Complex.I * ((θ₁ + 2 * Real.pi * (k : ℝ) : ℝ) : ℂ) =
        Complex.I * (θ₁ : ℂ) + ↑k * (2 * ↑Real.pi * Complex.I) by push_cast; ring]
    rw [Complex.exp_add, Complex.exp_int_mul_two_pi_mul_I, mul_one]
  rw [show Complex.I * (↑γ₁ * ↑t) = Complex.I * ((γ₁ * t : ℝ) : ℂ) by push_cast; ring]
  rw [hphase, sub_self, norm_zero]
  exact hε

/-- For any finite collection of positive frequencies, we can align the FIRST
    frequency exactly. Entry point for the tower construction. -/
theorem first_frequency_exact_rest_approximate
    {n : ℕ} (γ : Fin (n + 1) → ℝ) (hγ : ∀ i, γ i > 0)
    (θ : Fin (n + 1) → ℝ) (L : ℝ) :
    ∃ t : ℝ, t > L ∧ ∃ k : ℤ, γ 0 * t = θ 0 + 2 * Real.pi * k := by
  exact single_frequency_phase_alignment (hγ 0) (θ 0) L

/-- The key density lemma for multi-frequency alignment:
    if α and β are Q-linearly independent reals, then {mα + nβ : m,n ∈ ℤ}
    is dense in ℝ. -/
theorem dense_span_of_Q_independent {α β : ℝ}
    (hαβ : Irrational (α / β)) (_hβ_ne : β ≠ 0) :
    Dense (AddSubgroup.closure {α, β} : Set ℝ) := by
  rw [dense_addSubgroupClosure_pair_iff]
  exact hαβ

/-- From density of {mα + nβ}, extract the inhomogeneous approximation:
    for any target θ and ε > 0, ∃ m n with |mα + nβ - θ| < ε. -/
theorem inhomogeneous_2d_approx {α β : ℝ}
    (hαβ : Irrational (α / β)) (hβ_ne : β ≠ 0)
    (θ : ℝ) {ε : ℝ} (hε : ε > 0) :
    ∃ m n : ℤ, |m * α + n * β - θ| < ε := by
  have hd := dense_span_of_Q_independent hαβ hβ_ne
  rw [Metric.dense_iff] at hd
  obtain ⟨y, hy_mem, hy_close⟩ := hd θ ε hε
  rw [show ({α, β} : Set ℝ) = {α} ∪ {β} from by ext; simp [or_comm],
      AddSubgroup.closure_union,
      ← AddSubgroup.zmultiples_eq_closure, ← AddSubgroup.zmultiples_eq_closure,
      SetLike.mem_coe, AddSubgroup.mem_sup] at hy_close
  obtain ⟨a, ha, b, hb, rfl⟩ := hy_close
  rw [AddSubgroup.mem_zmultiples_iff] at ha hb
  obtain ⟨m, rfl⟩ := ha; obtain ⟨n, rfl⟩ := hb
  exact ⟨m, n, by
    simp only [zsmul_eq_mul, mul_one] at hy_mem ⊢
    rwa [Metric.mem_ball, Real.dist_eq] at hy_mem⟩

/-- Phase norm bound from arg approximation. -/
theorem inhomogeneous_phase_abs_bound
    {α θ : ℝ} {m : ℤ} {k : ℤ} {ε : ℝ}
    (hclose : |↑m * α - θ - ↑k * (2 * Real.pi)| < ε) :
    ‖Complex.exp (Complex.I * (↑m * α)) -
     Complex.exp (Complex.I * θ)‖ < ε := by
  set δ := ↑m * α - θ - ↑k * (2 * Real.pi) with hδ_def
  have hma : (↑m * α : ℝ) = θ + δ + ↑k * (2 * Real.pi) := by simp [hδ_def]; ring
  have key : Complex.exp (Complex.I * (↑m * α : ℂ)) =
      Complex.exp (Complex.I * (θ : ℂ)) * Complex.exp (Complex.I * (δ : ℂ)) := by
    rw [show (↑m * α : ℂ) = ((↑m * α : ℝ) : ℂ) from by push_cast; ring, hma]
    rw [show ((θ + δ + ↑k * (2 * Real.pi) : ℝ) : ℂ) =
        (θ : ℂ) + (δ : ℂ) + ↑k * (2 * ↑Real.pi) from by push_cast; ring]
    rw [show Complex.I * ((θ : ℂ) + (δ : ℂ) + ↑k * (2 * ↑Real.pi)) =
        Complex.I * (θ : ℂ) + Complex.I * (δ : ℂ) + ↑k * (2 * ↑Real.pi * Complex.I) by ring]
    rw [Complex.exp_add, Complex.exp_add, Complex.exp_int_mul_two_pi_mul_I, mul_one]
  rw [key]
  calc ‖Complex.exp (Complex.I * (θ : ℂ)) * Complex.exp (Complex.I * (δ : ℂ)) -
        Complex.exp (Complex.I * (θ : ℂ))‖
      = ‖Complex.exp (Complex.I * (θ : ℂ)) * (Complex.exp (Complex.I * (δ : ℂ)) - 1)‖ := by
        congr 1; ring
    _ = ‖Complex.exp (Complex.I * (θ : ℂ))‖ * ‖Complex.exp (Complex.I * (δ : ℂ)) - 1‖ :=
        norm_mul _ _
    _ = 1 * ‖Complex.exp (Complex.I * (δ : ℂ)) - 1‖ := by
        congr 1
        rw [show Complex.I * (θ : ℂ) = ↑θ * Complex.I from by push_cast; ring]
        exact Complex.norm_exp_ofReal_mul_I θ
    _ = ‖Complex.exp (Complex.I * (δ : ℂ)) - 1‖ := one_mul _
    _ ≤ |δ| := by
        calc ‖Complex.exp (Complex.I * (δ : ℂ)) - 1‖
            = ‖Complex.exp (Complex.I * (δ : ℂ)) - Complex.exp (Complex.I * 0)‖ := by
              simp
          _ ≤ |δ - 0| := complex_exp_I_sub_norm_le δ 0
          _ = |δ| := by simp
    _ < ε := hclose

/-! ### Part 7: Multi-frequency approximate alignment infrastructure -/

/-- For a single positive frequency, exact congruence solutions exist above
    any threshold. -/
theorem single_freq_exact_above_threshold
    {γ : ℝ} (hγ : γ > 0) (θ : ℝ) (L : ℝ) :
    ∃ t : ℝ, t > L ∧ ∃ k : ℤ, γ * t = θ + 2 * Real.pi * k :=
  single_frequency_phase_alignment hγ θ L

/-- For a single positive frequency γ, the exact congruence
    `∃ m : ℤ, t * γ - θ - m • (2π) = 0` holds for a dense set of t. -/
theorem exact_congruence_above_threshold
    {γ : ℝ} (hγ : γ > 0) (θ : ℝ) (L : ℝ) :
    ∃ t : ℝ, t > L ∧ ∃ m : ℤ, t * γ - θ - m • (2 * Real.pi) = 0 := by
  obtain ⟨t, ht_gt, k, hk⟩ := single_frequency_phase_alignment hγ θ L
  refine ⟨t, ht_gt, k, ?_⟩
  have : γ * t = θ + 2 * Real.pi * ↑k := hk
  simp only [zsmul_eq_mul]
  linarith

/-- Two-frequency mixed alignment with independent frequencies. -/
theorem two_freq_exact_plus_approx_phase
    {γ₁ γ₂ : ℝ} (hγ₁ : γ₁ > 0)
    (h_irr : Irrational (γ₂ / γ₁))
    (θ₁ θ₂ : ℝ) {ε : ℝ} (hε : ε > 0) :
    ∃ m : ℤ,
      (γ₁ * ((θ₁ + 2 * Real.pi * ↑m) / γ₁) = θ₁ + 2 * Real.pi * ↑m) ∧
      ‖Complex.exp (Complex.I * (γ₂ * ((θ₁ + 2 * Real.pi * ↑m) / γ₁))) -
       Complex.exp (Complex.I * θ₂)‖ < ε := by
  have hpi_ne : (2 * Real.pi : ℝ) ≠ 0 := ne_of_gt (by positivity)
  have h_ratio_irr : Irrational (2 * Real.pi * (γ₂ / γ₁) / (2 * Real.pi)) := by
    rw [show 2 * Real.pi * (γ₂ / γ₁) / (2 * Real.pi) = γ₂ / γ₁ from by field_simp]
    exact h_irr
  set α := 2 * Real.pi * (γ₂ / γ₁) with hα_def
  set target := θ₂ - γ₂ * θ₁ / γ₁ with htarget_def
  obtain ⟨m, j, happrox⟩ := inhomogeneous_1d_approx_mod h_ratio_irr target hε
  refine ⟨m, ?_⟩
  constructor
  · field_simp
  · have hval : γ₂ * ((θ₁ + 2 * Real.pi * ↑m) / γ₁) - θ₂ =
        ↑m * α - target := by
      rw [htarget_def, hα_def]; field_simp; ring
    have habs : |↑(1 : ℤ) * (γ₂ * ((θ₁ + 2 * Real.pi * ↑m) / γ₁)) - θ₂ -
        ↑j * (2 * Real.pi)| < ε := by
      simp only [Int.cast_one, one_mul]; rw [hval]; exact happrox
    have h := inhomogeneous_phase_abs_bound habs
    simp only [Int.cast_one, one_mul] at h
    convert h using 2
    push_cast; ring

/-- The set of exact solutions for a single frequency is periodic
    with period 2π/γ. Any interval of length ≥ 2π/γ contains at least one solution. -/
theorem exact_solutions_periodic
    {γ : ℝ} (hγ : γ > 0) (θ : ℝ) (a : ℝ)
    (b : ℝ) (hab : b - a ≥ 2 * Real.pi / γ) :
    ∃ t : ℝ, a ≤ t ∧ t ≤ b ∧ ∃ k : ℤ, γ * t = θ + 2 * Real.pi * k := by
  have hpi2 : (0 : ℝ) < 2 * Real.pi := by positivity
  set k₀ : ℤ := ⌈(a * γ - θ) / (2 * Real.pi)⌉ with hk₀_def
  set t₀ : ℝ := (θ + 2 * Real.pi * k₀) / γ with ht₀_def
  refine ⟨t₀, ?_, ?_, k₀, by rw [ht₀_def]; field_simp⟩
  · rw [ht₀_def, le_div_iff₀ hγ]
    have : (a * γ - θ) / (2 * Real.pi) ≤ k₀ := Int.le_ceil _
    have h1 : (a * γ - θ) ≤ (k₀ : ℝ) * (2 * Real.pi) := by
      rwa [div_le_iff₀ hpi2] at this
    linarith
  · rw [ht₀_def, div_le_iff₀ hγ]
    have hgap : (b - a) * γ ≥ 2 * Real.pi := by
      calc (b - a) * γ ≥ (2 * Real.pi / γ) * γ :=
            mul_le_mul_of_nonneg_right hab (le_of_lt hγ)
        _ = 2 * Real.pi := by field_simp
    have hceil_ub : (k₀ : ℝ) ≤ (a * γ - θ) / (2 * Real.pi) + 1 := by
      have h2 := Int.floor_le ((a * γ - θ) / (2 * Real.pi))
      have h3 := Int.ceil_le_floor_add_one ((a * γ - θ) / (2 * Real.pi))
      have h4 : (⌊(a * γ - θ) / (2 * Real.pi)⌋ : ℝ) + 1 ≤
          (a * γ - θ) / (2 * Real.pi) + 1 := by linarith
      have h5 : (k₀ : ℝ) ≤ ((⌊(a * γ - θ) / (2 * Real.pi)⌋ + 1 : ℤ) : ℝ) := by
        exact_mod_cast h3
      push_cast at h5; linarith
    have h_mul : (2 * Real.pi) * (k₀ : ℝ) ≤ (2 * Real.pi) * ((a * γ - θ) / (2 * Real.pi) + 1) :=
      mul_le_mul_of_nonneg_left hceil_ub (le_of_lt hpi2)
    rw [mul_add, mul_div_cancel₀ _ (ne_of_gt hpi2), mul_one] at h_mul
    linarith

/-! ### Part 8: Large-m 1D Kronecker and threshold infrastructure

The 1D Kronecker theorem gives ∃ m ∈ ℤ with phase alignment, but doesn't
control the size of m. For the tower construction, we need m > M for given M.

Key result: for irrational α/(2π), the phase alignment orbit visits every
ε-ball for ARBITRARILY LARGE m. This follows from the Dirichlet-shift
construction: get initial alignment m₀, then shift by multiples of a
"near-period" q from homogeneous Dirichlet.

Reference: Kronecker 1884; Hardy-Wright §23.8. -/

/-- **Quantitative near-period from homogeneous Dirichlet**:
    For irrational α/(2π) and N ≥ 1, there exists q with 1 ≤ q ≤ N
    and |q·α - p·2π| < 2π/N for some integer p. -/
theorem homogeneous_near_period
    {α : ℝ} (_hα : Irrational (α / (2 * Real.pi))) (N : ℕ) (hN : 0 < N) :
    ∃ q : ℕ, 1 ≤ q ∧ q ≤ N ∧
      ∃ p : ℤ, |↑q * α - ↑p * (2 * Real.pi)| < 2 * Real.pi / N := by
  have hpi : (0 : ℝ) < 2 * Real.pi := by positivity
  obtain ⟨q, hq_pos, hq_le, happrox⟩ :=
    DirichletApprox.dirichlet_approximation_simultaneous 1 (fun _ => α / (2 * Real.pi)) N hN
  refine ⟨q, hq_pos, by simp [pow_one] at hq_le; exact hq_le, ?_⟩
  have h0 := happrox (0 : Fin 1)
  rw [distToInt] at h0
  set r := round (α / (2 * Real.pi) * (q : ℝ)) with hr_def
  refine ⟨r, ?_⟩
  have hclose : |α / (2 * Real.pi) * (q : ℝ) - (r : ℝ)| < 1 / (N : ℝ) := h0
  have hN_pos : (0 : ℝ) < N := by exact_mod_cast hN
  calc |↑q * α - ↑r * (2 * Real.pi)|
      = |((α / (2 * Real.pi)) * ↑q - ↑r) * (2 * Real.pi)| := by
        congr 1; field_simp
    _ = |α / (2 * Real.pi) * ↑q - ↑r| * (2 * Real.pi) := by
        rw [abs_mul, abs_of_pos hpi]
    _ < 1 / ↑N * (2 * Real.pi) := by
        exact mul_lt_mul_of_pos_right hclose hpi
    _ = 2 * Real.pi / ↑N := by ring

/-- **Large-m 1D inhomogeneous Kronecker**: for irrational α/(2π), any target θ,
    ε > 0, and threshold M, there exists m > M with |m·α - θ - k·2π| < ε
    for some integer k.

    Construction: get initial alignment m₀ from 1D Kronecker. Get near-period q
    from homogeneous Dirichlet with N large. Shift m₀ by multiples of q:
    m = m₀ + ℓ·q. The phase error is bounded by initial error + ℓ · (2π/N). -/
theorem inhomogeneous_1d_approx_mod_large
    {α : ℝ} (hα : Irrational (α / (2 * Real.pi)))
    (θ : ℝ) {ε : ℝ} (hε : ε > 0) (M : ℝ) :
    ∃ m : ℤ, (M : ℝ) < m ∧
      ∃ k : ℤ, |↑m * α - θ - ↑k * (2 * Real.pi)| < ε := by
  have hpi : (0 : ℝ) < 2 * Real.pi := by positivity
  -- Step 1: Get initial alignment with ε/2 tolerance
  obtain ⟨m₀, j₀, hm₀⟩ := inhomogeneous_1d_approx_mod hα θ (ε := ε / 2) (by linarith)
  -- Step 2: Choose N for the near-period
  set ℓ_target := ⌈max (M - ↑m₀ + 1) 1⌉₊ with hℓ_target_def
  have hℓ_pos : 0 < ℓ_target := by
    have h1 : (1 : ℝ) ≤ max (M - ↑m₀ + 1) 1 := le_max_right _ _
    have h2 : (1 : ℝ) ≤ (⌈max (M - ↑m₀ + 1) 1⌉₊ : ℝ) := le_trans h1 (Nat.le_ceil _)
    have h3 : 1 ≤ ⌈max (M - ↑m₀ + 1) 1⌉₊ := by exact_mod_cast h2
    omega
  -- Choose N so that ℓ_target · (2π/N) < ε/2
  set N := ⌈(ℓ_target : ℝ) * (4 * Real.pi / ε)⌉₊ + 1 with hN_def
  have hN_pos : 0 < N := Nat.succ_pos _
  have hN_large : (ℓ_target : ℝ) * (2 * Real.pi / (N : ℝ)) < ε / 2 := by
    have hN_pos_real : (0 : ℝ) < N := by exact_mod_cast hN_pos
    have hN_ge : (N : ℝ) > (ℓ_target : ℝ) * (4 * Real.pi / ε) := by
      have := Nat.le_ceil ((ℓ_target : ℝ) * (4 * Real.pi / ε))
      push_cast at this ⊢; simp [hN_def]; linarith
    -- ℓ * (2π/N) < ε/2 ⟺ ℓ * 2π < N * ε/2 ⟺ ℓ * 4π/ε < N (using ε > 0)
    rw [show (ℓ_target : ℝ) * (2 * Real.pi / ↑N) =
        (ℓ_target : ℝ) * (2 * Real.pi) / ↑N from by ring]
    rw [div_lt_iff₀ hN_pos_real]
    calc (ℓ_target : ℝ) * (2 * Real.pi)
        = (ℓ_target : ℝ) * (4 * Real.pi / ε) * (ε / 2) := by field_simp; ring
      _ < ↑N * (ε / 2) := mul_lt_mul_of_pos_right hN_ge (by linarith)
      _ = ε / 2 * ↑N := by ring
  -- Step 3: Get near-period q from homogeneous Dirichlet
  obtain ⟨q, hq_pos, _hq_le, p, hq_close⟩ := homogeneous_near_period hα N hN_pos
  -- Step 4: Set m = m₀ + ℓ_target · q
  set m := m₀ + (ℓ_target : ℤ) * (q : ℤ) with hm_def
  have hm_large : (M : ℝ) < (m : ℝ) := by
    push_cast [hm_def]
    have hq_ge : (q : ℝ) ≥ 1 := by exact_mod_cast hq_pos
    have hℓ_ge : (ℓ_target : ℝ) ≥ max (M - ↑m₀ + 1) 1 := by exact_mod_cast Nat.le_ceil _
    have h1 : (ℓ_target : ℝ) ≥ M - ↑m₀ + 1 := le_trans (le_max_left _ _) hℓ_ge
    have h2 : (ℓ_target : ℝ) * (q : ℝ) ≥ (ℓ_target : ℝ) * 1 :=
      mul_le_mul_of_nonneg_left hq_ge (by exact_mod_cast Nat.zero_le ℓ_target)
    linarith
  -- Step 5: Phase error bound
  set k := j₀ + (ℓ_target : ℤ) * p with hk_def
  refine ⟨m, hm_large, k, ?_⟩
  have key : ↑m * α - θ - ↑k * (2 * Real.pi) =
      (↑m₀ * α - θ - ↑j₀ * (2 * Real.pi)) +
      (ℓ_target : ℝ) * (↑q * α - ↑p * (2 * Real.pi)) := by
    push_cast [hm_def, hk_def]; ring
  rw [key]
  calc |↑m₀ * α - θ - ↑j₀ * (2 * Real.pi) +
        ↑ℓ_target * (↑q * α - ↑p * (2 * Real.pi))|
      ≤ |↑m₀ * α - θ - ↑j₀ * (2 * Real.pi)| +
        |↑ℓ_target * (↑q * α - ↑p * (2 * Real.pi))| := abs_add_le _ _
    _ = |↑m₀ * α - θ - ↑j₀ * (2 * Real.pi)| +
        (ℓ_target : ℝ) * |↑q * α - ↑p * (2 * Real.pi)| := by
        congr 1; rw [abs_mul, abs_of_nonneg]; exact_mod_cast Nat.zero_le ℓ_target
    _ < ε / 2 + (ℓ_target : ℝ) * (2 * Real.pi / ↑N) := by
        exact add_lt_add hm₀ (mul_lt_mul_of_pos_left hq_close (by exact_mod_cast hℓ_pos))
    _ < ε / 2 + ε / 2 := by linarith [hN_large]
    _ = ε := by ring

/-- **Single-frequency arg-approximate alignment above threshold**. -/
theorem single_freq_arg_approx_above_threshold
    {γ : ℝ} (hγ : γ > 0) (φ : ℝ) (L : ℝ) {ε : ℝ} (hε : ε > 0) :
    ∃ t : ℝ, t > L ∧
      ∃ k : ℤ, |t * γ - φ - ↑k * (2 * Real.pi)| ≤ ε := by
  obtain ⟨t, ht, k, hk⟩ := exact_congruence_above_threshold hγ φ L
  refine ⟨t, ht, k, ?_⟩
  simp only [zsmul_eq_mul] at hk
  have : t * γ - φ - ↑k * (2 * Real.pi) = 0 := by linarith
  rw [this, abs_zero]; linarith

/-- **Two-frequency exact+approx above threshold via Dirichlet shift**:
    For γ₁ > 0 with γ₂/γ₁ irrational, targets φ₁ φ₂, threshold L, ε > 0:
    ∃ t > L with γ₁t = φ₁ + 2πk₁ (exact) and |γ₂t - φ₂ - 2πk₂| < ε (approx).

    Uses `inhomogeneous_1d_approx_mod_large` to find m large enough that
    t = (φ₁ + 2πm)/γ₁ > L while maintaining second-frequency alignment. -/
theorem two_freq_arg_approx_above_threshold
    {γ₁ γ₂ : ℝ} (hγ₁ : γ₁ > 0) (_hγ₂ : γ₂ > 0)
    (h_irr : Irrational (γ₂ / γ₁))
    (φ₁ φ₂ : ℝ) (L : ℝ) {ε : ℝ} (hε : ε > 0) :
    ∃ t : ℝ, t > L ∧
      (∃ k₁ : ℤ, t * γ₁ - φ₁ - ↑k₁ * (2 * Real.pi) = 0) ∧
      (∃ k₂ : ℤ, |t * γ₂ - φ₂ - ↑k₂ * (2 * Real.pi)| < ε) := by
  have hpi : (0 : ℝ) < 2 * Real.pi := by positivity
  have hγ₁_ne : γ₁ ≠ 0 := ne_of_gt hγ₁
  set α := 2 * Real.pi * (γ₂ / γ₁) with hα_def
  set τ := φ₂ - γ₂ * φ₁ / γ₁ with hτ_def
  have h_α_irr : Irrational (α / (2 * Real.pi)) := by
    rw [hα_def, show 2 * Real.pi * (γ₂ / γ₁) / (2 * Real.pi) = γ₂ / γ₁ by field_simp]
    exact h_irr
  set M_val := (L * γ₁ - φ₁) / (2 * Real.pi) with hM_def
  -- By large-m Kronecker, ∃ m > M_val with |m·α - τ - k·2π| < ε
  obtain ⟨m, hm_large, k₂, hm_approx⟩ :=
    inhomogeneous_1d_approx_mod_large h_α_irr τ hε M_val
  set t := (φ₁ + 2 * Real.pi * ↑m) / γ₁ with ht_def
  refine ⟨t, ?_, ?_, ?_⟩
  · -- t > L
    rw [ht_def, gt_iff_lt, lt_div_iff₀ hγ₁]
    have : (M_val : ℝ) < (m : ℝ) := hm_large
    rw [hM_def] at this
    have := (div_lt_iff₀ hpi).mp this
    linarith
  · -- First frequency exact
    refine ⟨m, ?_⟩
    rw [ht_def]; field_simp; ring
  · -- Second frequency approximate
    refine ⟨k₂, ?_⟩
    have key : t * γ₂ - φ₂ - ↑k₂ * (2 * Real.pi) =
        ↑m * α - τ - ↑k₂ * (2 * Real.pi) := by
      rw [ht_def, hτ_def, hα_def]; field_simp; ring
    rw [key]; exact hm_approx

/-- Phase-norm bound from arg-approximation. -/
theorem phase_norm_of_arg_approx
    {t γ φ : ℝ} {k : ℤ} {ε : ℝ}
    (hclose : |t * γ - φ - ↑k * (2 * Real.pi)| < ε) :
    ‖Complex.exp (Complex.I * (t * γ)) -
     Complex.exp (Complex.I * φ)‖ < ε := by
  have h : |↑(1 : ℤ) * (t * γ) - φ - ↑k * (2 * Real.pi)| < ε := by
    simpa using hclose
  have := inhomogeneous_phase_abs_bound h
  simpa using this

/-! ### Part 9: N-dimensional inhomogeneous Kronecker infrastructure

For the Littlewood tower construction, we need to align finitely many
zeta-zero phases simultaneously. The approach:

1. **Single-zero case** (T chosen with N(T) = 1): EXACT alignment via
   `exact_congruence_above_threshold`. No irrationality needed.

2. **Two-zero case** (N(T) = 2): First frequency exact, second approximate,
   via `two_freq_arg_approx_above_threshold`. Needs γ₂/γ₁ irrational.

3. **General n-zero case**: Requires Q-linear independence of
   {1, γ₁/γ₀, ..., γₙ/γ₀} (Kronecker's theorem on the n-torus).
   The full proof uses either Pontryagin duality or the structure theorem
   for closed subgroups of ℝⁿ, neither of which is in Mathlib.
   For n ≥ 3, we provide the key BUILDING BLOCKS (shift refinement,
   irrationality preservation) that enable the inductive proof.

For the specific Littlewood application, choosing T with N(T) ≤ 2
suffices: the tower height bound only needs N(T)/(T+1) > 0, which
holds for T ≈ 15 (giving N(T) = 1, the first zero γ₁ ≈ 14.13).
-/

/-- Multiplication of an irrational number by a nonzero natural number
    preserves irrationality. If α is irrational and q ≥ 1, then q·α is irrational. -/
theorem irrational_natCast_mul' {α : ℝ} (hα : Irrational α) {q : ℕ} (hq : 1 ≤ q) :
    Irrational ((q : ℝ) * α) :=
  hα.natCast_mul (by omega)

/-- Multiplication of an irrational by a nonzero integer preserves irrationality. -/
theorem irrational_intCast_mul' {α : ℝ} (hα : Irrational α) {q : ℤ} (hq : q ≠ 0) :
    Irrational ((q : ℝ) * α) :=
  hα.intCast_mul hq

/-- Irrationality of q·α/(2π) from irrationality of α/(2π), for q ≥ 1.
    Key lemma for the inductive Kronecker construction: the near-period
    q from Dirichlet preserves the irrationality condition needed for
    the next 1D Kronecker application. -/
theorem irrational_natCast_mul_div_two_pi
    {α : ℝ} (hα : Irrational (α / (2 * Real.pi))) {q : ℕ} (hq : 1 ≤ q) :
    Irrational ((q : ℝ) * α / (2 * Real.pi)) := by
  rw [show (q : ℝ) * α / (2 * Real.pi) = (q : ℝ) * (α / (2 * Real.pi)) by ring]
  exact irrational_natCast_mul' hα hq

/-- The exact solution set for a single frequency has BOUNDED GAPS:
    any interval of length ≥ 2π/γ contains at least one solution
    t with γ·t ≡ θ (mod 2π). This is the key structural property
    that enables inductive multi-frequency alignment. -/
theorem exact_solutions_bounded_gaps
    {γ : ℝ} (hγ : γ > 0) (θ : ℝ) :
    ∀ a : ℝ, ∃ t : ℝ, a ≤ t ∧ t ≤ a + 2 * Real.pi / γ ∧
      ∃ k : ℤ, γ * t = θ + 2 * Real.pi * k := by
  intro a
  obtain ⟨t, ha, ht, k, hk⟩ := exact_solutions_periodic hγ θ a (a + 2 * Real.pi / γ) (by linarith)
  exact ⟨t, ha, ht, k, hk⟩

/-- **Single-zero phase alignment** (the key case for Littlewood):
    When the zero cutoff T is chosen with only ONE zero γ₁ below T,
    we need only 1D Kronecker. This always works with EXACT alignment. -/
theorem single_zero_phase_alignment
    {γ₁ : ℝ} (hγ₁ : γ₁ > 0) (θ : ℝ) (L : ℝ) :
    ∃ t : ℝ, t > L ∧
      (∃ k : ℤ, t * γ₁ - θ - ↑k * (2 * Real.pi) = 0) ∧
      ‖Complex.exp (Complex.I * (γ₁ * t)) -
       Complex.exp (Complex.I * θ)‖ = 0 := by
  obtain ⟨t, ht, k, hk⟩ := exact_congruence_above_threshold hγ₁ θ L
  simp only [zsmul_eq_mul] at hk
  refine ⟨t, ht, ⟨k, hk⟩, ?_⟩
  have hphase : γ₁ * t = θ + 2 * Real.pi * ↑k := by linarith
  rw [show Complex.I * (↑γ₁ * ↑t) = Complex.I * ((γ₁ * t : ℝ) : ℂ) by push_cast; ring]
  rw [hphase]
  rw [show ((θ + 2 * Real.pi * ↑k : ℝ) : ℂ) = (θ : ℂ) + ↑k * (2 * ↑Real.pi) by push_cast; ring]
  rw [show Complex.I * ((θ : ℂ) + ↑k * (2 * ↑Real.pi)) =
      Complex.I * (θ : ℂ) + ↑k * (2 * ↑Real.pi * Complex.I) by ring]
  rw [Complex.exp_add, Complex.exp_int_mul_two_pi_mul_I, mul_one, sub_self, norm_zero]

/-- **Two-zero phase alignment** with irrationality:
    When there are exactly two zeros γ₁, γ₂ with γ₂/γ₁ irrational,
    the first is aligned exactly and the second approximately.
    Both arg and phase-norm bounds are provided. -/
theorem two_zero_phase_alignment
    {γ₁ γ₂ : ℝ} (hγ₁ : γ₁ > 0) (hγ₂ : γ₂ > 0)
    (h_irr : Irrational (γ₂ / γ₁))
    (θ₁ θ₂ : ℝ) {ε : ℝ} (hε : ε > 0) (L : ℝ) :
    ∃ t : ℝ, t > L ∧
      (∃ k₁ : ℤ, t * γ₁ - θ₁ - ↑k₁ * (2 * Real.pi) = 0) ∧
      (∃ k₂ : ℤ, |t * γ₂ - θ₂ - ↑k₂ * (2 * Real.pi)| < ε) ∧
      ‖Complex.exp (Complex.I * (γ₁ * t)) -
       Complex.exp (Complex.I * θ₁)‖ = 0 ∧
      ‖Complex.exp (Complex.I * (γ₂ * t)) -
       Complex.exp (Complex.I * θ₂)‖ < ε :=
  two_freq_arg_approx_above_threshold hγ₁ hγ₂ h_irr θ₁ θ₂ L hε
    |>.imp fun t ⟨ht, hk₁, hk₂⟩ => by
  refine ⟨ht, hk₁, hk₂, ?_, ?_⟩
  · -- Exact phase alignment for γ₁
    obtain ⟨k₁, hk₁⟩ := hk₁
    have hphase : γ₁ * t = θ₁ + 2 * Real.pi * ↑k₁ := by linarith
    rw [show Complex.I * (↑γ₁ * ↑t) = Complex.I * ((γ₁ * t : ℝ) : ℂ) by push_cast; ring]
    rw [hphase]
    rw [show ((θ₁ + 2 * Real.pi * ↑k₁ : ℝ) : ℂ) = (θ₁ : ℂ) + ↑k₁ * (2 * ↑Real.pi) by push_cast; ring]
    rw [show Complex.I * ((θ₁ : ℂ) + ↑k₁ * (2 * ↑Real.pi)) =
        Complex.I * (θ₁ : ℂ) + ↑k₁ * (2 * ↑Real.pi * Complex.I) by ring]
    rw [Complex.exp_add, Complex.exp_int_mul_two_pi_mul_I, mul_one, sub_self, norm_zero]
  · -- Approximate phase alignment for γ₂
    obtain ⟨k₂, hk₂⟩ := hk₂
    have h := phase_norm_of_arg_approx hk₂
    simp only [show (↑γ₂ : ℂ) * ↑t = ↑t * ↑γ₂ from mul_comm _ _] at h ⊢
    exact h

/-- **Single-frequency phase alignment for Finset with one element**:
    When the finite set of frequencies is a singleton {γ₀}, exact
    phase alignment is always achievable. This is the Littlewood-relevant
    case when T is chosen so that N(T) = 1. -/
theorem singleton_finset_phase_alignment
    {γ₀ : ℝ} (hγ₀ : γ₀ > 0) (θ : ℝ) {ε : ℝ} (hε : ε > 0) (L : ℝ) :
    ∃ t : ℝ, t > L ∧
      ∀ γ ∈ ({γ₀} : Finset ℝ),
        ∃ k : ℤ, |t * γ - θ - ↑k * (2 * Real.pi)| < ε := by
  obtain ⟨t, ht, k, hk⟩ := exact_congruence_above_threshold hγ₀ θ L
  refine ⟨t, ht, fun γ hγ => ?_⟩
  simp only [Finset.mem_singleton] at hγ
  subst hγ
  exact ⟨k, by
    simp only [zsmul_eq_mul] at hk
    have : t * γ - θ - ↑k * (2 * Real.pi) = 0 := by linarith
    rw [this, abs_zero]; exact hε⟩

/-- **Two-element Finset phase alignment**: When the finite set has exactly
    two elements with irrational ratio, achieve exact alignment on the first
    and approximate on the second. -/
theorem pair_finset_phase_alignment
    {γ₁ γ₂ : ℝ} (hγ₁ : γ₁ > 0) (hγ₂ : γ₂ > 0) (hne : γ₁ ≠ γ₂)
    (h_irr : Irrational (γ₂ / γ₁))
    (θ : ℝ → ℝ) {ε : ℝ} (hε : ε > 0) (L : ℝ) :
    ∃ t : ℝ, t > L ∧
      ∀ γ ∈ ({γ₁, γ₂} : Finset ℝ),
        ∃ k : ℤ, |t * γ - θ γ - ↑k * (2 * Real.pi)| < ε := by
  obtain ⟨t, ht, hk₁, hk₂⟩ :=
    two_freq_arg_approx_above_threshold hγ₁ hγ₂ h_irr (θ γ₁) (θ γ₂) L hε
  refine ⟨t, ht, fun γ hγ => ?_⟩
  simp only [Finset.mem_insert, Finset.mem_singleton] at hγ
  rcases hγ with rfl | rfl
  · -- γ = γ₁: exact alignment
    obtain ⟨k₁, hk₁⟩ := hk₁
    exact ⟨k₁, by
      have : t * γ - θ γ - ↑k₁ * (2 * Real.pi) = 0 := by linarith
      rw [this, abs_zero]; exact hε⟩
  · -- γ = γ₂: approximate alignment
    exact hk₂

/-- **Phase-norm alignment for singleton Finset of zeta zeros**:
    Provides the phase alignment in norm form needed by the tower witness.
    For a single zero γ₁, alignment is exact (error = 0 < ε). -/
theorem single_zero_finset_phase_norm_alignment
    {γ₁ : ℝ} (hγ₁ : γ₁ > 0) (θ : ℝ) {ε : ℝ} (hε : ε > 0) (L : ℝ) :
    ∃ t : ℝ, t > L ∧
      ‖Complex.exp (Complex.I * (γ₁ * t)) -
       Complex.exp (Complex.I * θ)‖ < ε := by
  obtain ⟨t, ht, _, hphase⟩ := single_zero_phase_alignment hγ₁ θ L
  exact ⟨t, ht, by rw [hphase]; exact hε⟩

/-- **Multi-frequency alignment reduces to single via large T choice**:
    For any γ₁ > 0 (the first zeta zero ordinate), target phase w,
    precision ε > 0, and threshold L, there exists t > L with
    ‖e^{iγ₁t} - e^{iw}‖ < ε AND the tower height bound
    with N(T) = 1 (taking T slightly above γ₁).

    This is the "simpler alternative" for the Littlewood tower: by choosing
    T ≈ 15 (so N(T) = 1), the multi-frequency alignment problem reduces
    to a single-frequency problem, which is solved exactly. -/
theorem single_zero_tower_compatible_alignment
    {γ₁ : ℝ} (hγ₁ : γ₁ > 0) (w : ℝ) (L : ℝ) :
    ∃ t : ℝ, t > L ∧
      (∃ k : ℤ, γ₁ * t = w + 2 * Real.pi * k) ∧
      ‖Complex.exp (Complex.I * (γ₁ * t)) -
       Complex.exp (Complex.I * w)‖ = 0 := by
  obtain ⟨t, ht, k, hk⟩ := single_frequency_phase_alignment hγ₁ w L
  refine ⟨t, ht, ⟨k, hk⟩, ?_⟩
  rw [show Complex.I * (↑γ₁ * ↑t) = Complex.I * ((γ₁ * t : ℝ) : ℂ) by push_cast; ring]
  rw [hk]
  rw [show ((w + 2 * Real.pi * ↑k : ℝ) : ℂ) = (w : ℂ) + ↑k * (2 * ↑Real.pi) by push_cast; ring]
  rw [show Complex.I * ((w : ℂ) + ↑k * (2 * ↑Real.pi)) =
      Complex.I * (w : ℂ) + ↑k * (2 * ↑Real.pi * Complex.I) by ring]
  rw [Complex.exp_add, Complex.exp_int_mul_two_pi_mul_I, mul_one, sub_self, norm_zero]

end Kronecker

end
