#!/usr/bin/env bash
set -euo pipefail

# Reproducible external Lean theorem harvest scanner.
# - Clones/updates candidate repos under WORKDIR (default: /tmp/lean-hunt)
# - Emits a compact machine-readable summary TSV
# - Emits grep-based key-hit traces for fast theorem-path triage

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKDIR="${WORKDIR:-/tmp/lean-hunt}"
OUT_DIR="$REPO_ROOT/docs/review_graphs"
SUMMARY_OUT="$OUT_DIR/external_repo_harvest_summary.tsv"
HITS_OUT="$OUT_DIR/external_repo_harvest_keyhits.txt"

mkdir -p "$WORKDIR" "$OUT_DIR"

CANDIDATES=(
  "PrimeNumberTheoremAnd|https://github.com/AlexKontorovich/PrimeNumberTheoremAnd.git"
  "strongpnt|https://github.com/math-inc/strongpnt.git"
  "DirichletNonvanishing|https://github.com/CBirkbeck/DirichletNonvanishing.git"
  "PNT|https://github.com/jonwashburn/PNT.git"
  "RiemannHypothesisCurves|https://github.com/math-inc/RiemannHypothesisCurves.git"
  "stirling|https://github.com/mo271/stirling.git"
  "Lean-RH|https://github.com/AlexKontorovich/Lean-RH.git"
  "lean-riemann-hypothesis|https://github.com/bhgomes/lean-riemann-hypothesis.git"
  "riemann-hypothesis-lean4-formal-proof|https://github.com/mimic1693/riemann-hypothesis-lean4-formal-proof.git"
  "Riemann-adelic|https://github.com/motanova84/Riemann-adelic.git"
)

KEY_PATTERNS='WienerIkehara|SmoothedChebyshev|ExplicitFormula|Perron|Mellin|residue|contour|logDeriv|vonMangoldt|ChebyshevPsi|Stirling|van der Corput|phase|TargetTower|ExactSeed'

echo "syncing external repos in $WORKDIR..."
for spec in "${CANDIDATES[@]}"; do
  name="${spec%%|*}"
  url="${spec#*|}"
  dir="$WORKDIR/$name"
  if [ -d "$dir/.git" ]; then
    git -C "$dir" fetch --depth 1 origin >/dev/null 2>&1 || true
    head_ref="$(git -C "$dir" symbolic-ref refs/remotes/origin/HEAD 2>/dev/null || true)"
    if [ -n "$head_ref" ]; then
      default_branch="${head_ref#refs/remotes/origin/}"
      git -C "$dir" reset --hard "origin/$default_branch" >/dev/null 2>&1 || true
    fi
  else
    git clone --depth 1 "$url" "$dir" >/dev/null 2>&1 || true
  fi
done

{
  printf "repo\turl\tdefault_branch\tcommit\tlean_files\taxiom_postulate_lines\tsorry_lines\tadmit_lines\ttoolchain\tlicense_line\n"
  for spec in "${CANDIDATES[@]}"; do
    name="${spec%%|*}"
    url="${spec#*|}"
    dir="$WORKDIR/$name"

    if [ ! -d "$dir" ]; then
      printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" "$name" "$url" "missing" "missing" "0" "0" "0" "0" "missing" "missing"
      continue
    fi

    default_branch="$(git -C "$dir" symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@refs/remotes/origin/@@' || true)"
    commit="$(git -C "$dir" rev-parse --short HEAD 2>/dev/null || true)"
    lean_files="$(find "$dir" -name '*.lean' | wc -l | tr -d ' ')"
    axiom_lines="$( (rg -n '\baxiom\b|\bpostulate\b' "$dir" --glob '*.lean' || true) | wc -l | tr -d ' ' )"
    sorry_lines="$( (rg -n '\bsorry\b' "$dir" --glob '*.lean' || true) | wc -l | tr -d ' ' )"
    admit_lines="$( (rg -n '\badmit\b' "$dir" --glob '*.lean' || true) | wc -l | tr -d ' ' )"

    toolchain="(none)"
    if [ -f "$dir/lean-toolchain" ]; then
      toolchain="$(cat "$dir/lean-toolchain" | tr '\t' ' ' | sed 's/[[:space:]]\+/ /g;s/^ //;s/ $//')"
    fi

    license_line="none"
    if [ -f "$dir/LICENSE" ]; then
      license_line="$(head -n 1 "$dir/LICENSE" | tr '\t' ' ' | sed 's/[[:space:]]\+/ /g;s/^ //;s/ $//')"
    elif [ -f "$dir/LICENSE.md" ]; then
      license_line="$(head -n 1 "$dir/LICENSE.md" | tr '\t' ' ' | sed 's/[[:space:]]\+/ /g;s/^ //;s/ $//')"
    fi

    printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
      "$name" "$url" "${default_branch:-unknown}" "${commit:-unknown}" "$lean_files" \
      "$axiom_lines" "$sorry_lines" "$admit_lines" "$toolchain" "$license_line"
  done
} > "$SUMMARY_OUT"

{
  printf "# External Lean Harvest Key Hits\n\n"
  printf "Generated by: scripts/external_repo_harvest_scan.sh\n"
  printf "Workdir: %s\n\n" "$WORKDIR"
  for spec in "${CANDIDATES[@]}"; do
    name="${spec%%|*}"
    dir="$WORKDIR/$name"
    printf "## %s\n\n" "$name"
    if [ ! -d "$dir" ]; then
      printf "missing clone\n\n"
      continue
    fi
    rg -n "$KEY_PATTERNS" "$dir" --glob '*.lean' | head -n 180 || true
    printf "\n"
  done
} > "$HITS_OUT"

echo "wrote $SUMMARY_OUT"
echo "wrote $HITS_OUT"
